INSERT INTO Project.dbo.Category (CategoryName, Description)
    VALUES
    ('coffee', 'Lorem ipsum dolor sit amet.'),
    ('tea','Lorem ipsum dolor sit amet.'),
    ('juices','Lorem ipsum dolor sit amet.'),
    ('soda','Lorem ipsum dolor sit amet.'),
    ('soups','Lorem ipsum dolor sit amet.'),
    ('salads','Lorem ipsum dolor sit amet.'),
    ('dips','Lorem ipsum dolor sit amet.'),
    ('cold appetizers','Lorem ipsum dolor sit amet.'),
    ('hot appetizers','Lorem ipsum dolor sit amet.'),
    ('meat dishes','Lorem ipsum dolor sit amet.'),
    ('fish dishes','Lorem ipsum dolor sit amet.'),
    ('vegetarian dishes','Lorem ipsum dolor sit amet.'),
    ('pasta','Lorem ipsum dolor sit amet.'),
    ('casseroles','Lorem ipsum dolor sit amet.'),
    ('cakes','Lorem ipsum dolor sit amet.'),
    ('ice cream','Lorem ipsum dolor sit amet.'),
    ('fruit','Lorem ipsum dolor sit amet.'),
    ('puddings','Lorem ipsum dolor sit amet.'),
    ('custards','Lorem ipsum dolor sit amet.'),
    ('cheese','Lorem ipsum dolor sit amet.'),
    ('sauces','Lorem ipsum dolor sit amet.'),
    ('spices','Lorem ipsum dolor sit amet.'),
    ('sea food','Lorem ipsum dolor sit amet.'),
    ('breads','Lorem ipsum dolor sit amet.'),
    ('biscuits','Lorem ipsum dolor sit amet.'),
    ('cookies','Lorem ipsum dolor sit amet.'),
    ('cereals','Lorem ipsum dolor sit amet.'),
    ('nuts','Lorem ipsum dolor sit amet.'),
    ('chocolate','Lorem ipsum dolor sit amet.'),
    ('sweets','Lorem ipsum dolor sit amet.'),
    ('candies','Lorem ipsum dolor sit amet.')
