INSERT INTO Project.dbo.Cities
    VALUES
        ('Kutno'),
        ('Kędzierzyn-Koźle'),
        ('Zduńska Wola'),
        ('Tarnobrzeg'),
        ('Chorzów'),
        ('Polkowice'),
        ('Nowy Targ'),
        ('Łowicz'),
        ('Tychy'),
        ('Kwidzyn'),
        ('Skierniewice'),
        ('Września'),
        ('Zgorzelec'),
        ( 'Dzierżoniów'),
        ( 'Żywiec'),
        ('Kościan'),
        ( 'Świecie'),
        ('Brzeg'),
        ('Kościerzyna'),
        ('Inowrocław'),
        ('Koszalin'),
        ('Mikołów'),
        ('Legionowo'),
        ('Biała Podlaska'),
        ('Kluczbork'),
        ('Czeladź'),
        ('Bochnia'),
        ('Ruda Śląska'),
        ('Łuków'),
        ('Siedlce'),
        ('Lublin'),
        ('Chrzanów'),
        ('Jarocin'),
        ('Katowice'),
        ('Bartoszyce'),
        ('Ostróda'),
        ('Chełm'),
        ('Augustów'),
        ('Żagań'),
        ('Świętochłowice'),
        ('Wołomin'),
        ('Zawiercie'),
        ('Poznań'),
        ('Siemianowice Śląskie'),
        ('Chojnice'),
        ('Kalisz'),
        ('Ząbki'),
        ('Wałbrzych'),
        ('Ciechanów'),
        ('Płock'),
        ('Mysłowice'),
        ('Sopot'),
        ('Gdańsk'),
        ('Pruszcz Gdański'),
        ('Gliwice'),
        ('Kętrzyn'),
        ('Oświęcim'),
        ('Jasło'),
        ('Giżycko'),
        ('Lubin'),
        ('Nowa Ruda'),
        ('Mława'),
        ('Płońsk'),
        ('Jaworzno'),
        ('Przemyśl'),
        ('Mińsk Mazowiecki'),
        ('Wrocław'),
        ('Sieradz'),
        ('Piekary Śląskie'),
        ('Nysa'),
        ('Grudziądz'),
        ('Koło'),
        ('Gdynia'),
        ('Tarnów'),
        ('Świdnica'),
        ('Luboń'),
        ('Goleniów'),
        ('Zakopane'),
        ('Sandomierz'),
        ('Zamość'),
        ('Dębica'),
        ('Piaseczno'),
        ('Jastrzębie-Zdrój'),
        ('Słupsk'),
        ('Bielawa'),
        ('Żary'),
        ('Kłodzko'),
        ('Włocławek'),
        ('Żyrardów'),
        ('Gniezno'),
        ('Warszawa'),
        ('Police'),
        ('Opole'),
        ('Tczew'),
        ('Otwock'),
        ('Tarnowskie Góry'),
        ('Stalowa Wola'),
        ('Wodzisław Śląski'),
        ('Białystok'),
        ('Pszczyna'),
        ('Racibórz'),
        ('Krotoszyn'),
        ('Marki'),
        ('Iława'),
        ('Ełk'),
        ('Legnica'),
        ('Wejherowo'),
        ('Środa Wielkopolska'),
        ('Mielec'),
        ('Śrem'),
        ('Pruszków'),
        ('Częstochowa'),
        ('Rzeszów'),
        ('Starachowice'),
        ('Gorzów Wielkopolski'),
        ('Puławy'),
        ('Olkusz'),
        ('Świebodzice'),
        ('Gorlice'),
        ('Bielsko-Biała'),
        ('Piła'),
        ('Toruń'),
        ('Oława'),
        ('Oleśnica'),
        ('Skawina'),
        ('Świdnik'),
        ('Łaziska Górne'),
        ('Kielce'),
        ('Jarosław'),
        ('Ostrowiec Świętokrzyski'),
        ('Stargard Szczeciński'),
        ('Knurów'),
        ('Myszków'),
        ('Swarzędz'),
        ('Ostrołęka'),
        ('Łódź'),
        ('Kołobrzeg'),
        ('Olsztyn'),
        ('Suwałki'),
        ('Będzin'),
        ('Wyszków'),
        ('Cieszyn'),
        ('Czechowice-Dziedzice'),
        ('Ostrów Wielkopolski'),
        ('Sochaczew'),
        ('Biłgoraj'),
        ('Piotrków Trybunalski'),
        ('Łomża'),
        ('Nowy Dwór Mazowiecki'),
        ('Sosnowiec'),
        ('Jawor'),
        ('Świnoujście'),
        ('Grodzisk Mazowiecki'),
        ('Dąbrowa Górnicza'),
        ('Elbląg'),
        ('Turek'),
        ('Brodnica'),
        ('Zielona Góra'),
        ('Piastów'),
        ('Rumia'),
        ('Czerwionka-Leszczyny'),
        ('Szczecin'),
        ('Głogów'),
        ('Szczecinek'),
        ('Bydgoszcz'),
        ('Wągrowiec'),
        ('Bytom'),
        ('Białogard'),
        ('Starogard Gdański'),
        ('Pabianice'),
        ('Wałcz'),
        ('Krosno'),
        ('Sanok'),
        ('Lubliniec'),
        ('Skarżysko-Kamienna'),
        ('Zgierz'),
        ('Kraśnik'),
        ('Zabrze'),
        ('Leszno'),
        ('Bolesławiec'),
        ('Szczytno'),
        ('Nowa Sól'),
        ('Malbork'),
        ('Kraków'),
        ('Ostrów Mazowiecka'),
        ('Lubartów'),
        ('Zambrów'),
        ('Bełchatów'),
        ('Radom'),
        ('Nowy Sącz'),
        ('Radomsko'),
        ('Jelenia Góra'),
        ('Lębork'),
        ('Bielsk Podlaski'),
        ('Żory'),
        ('Wieluń'),
        ('Konin'),
        ('Reda'),
        ('Tomaszów Mazowiecki'),
        ('Rybnik')