EXEC addClient @ClientType='I', @FirstName='Fryderyk', @LastName=Danisz, @Email='vkuciel@example.net', @Phone='515476533', @AddressID=362
EXEC addClient @ClientType='I', @FirstName='Kaja', @LastName=Prokopczyk, @Email='wojciech00@example.net', @Phone='570901004', @AddressID=140
EXEC addClient @ClientType='I', @FirstName='Damian', @LastName=Wawrzynowicz, @Email='machonmarika@example.com', @Phone='48323685936', @AddressID=370
EXEC addClient @ClientType='I', @FirstName='Sara', @LastName=Orkisz, @Email='alansych@example.org', @Phone='48505552223', @AddressID=459
EXEC addClient @ClientType='I', @FirstName='Sonia', @LastName=Gogół, @Email='julian46@example.org', @Phone='48535185836', @AddressID=387
EXEC addClient @ClientType='I', @FirstName='Oskar', @LastName=Oleksiewicz, @Email='bartkowiczjedrzej@example.com', @Phone='797361832', @AddressID=121
EXEC addClient @ClientType='I', @FirstName='Nicole', @LastName=Smal, @Email='ybik@example.com', @Phone='721618281', @AddressID=391
EXEC addClient @ClientType='I', @FirstName='Kornelia', @LastName=Gryga, @Email='oliwier14@example.com', @Phone='223516269', @AddressID=18
EXEC addClient @ClientType='I', @FirstName='Kamil', @LastName=Guźniczak, @Email='mieszkopolakiewicz@example.net', @Phone='48660867234', @AddressID=443
EXEC addClient @ClientType='I', @FirstName='Malwina', @LastName=Sterna, @Email='fabian18@example.net', @Phone='729775988', @AddressID=189
EXEC addClient @ClientType='I', @FirstName='Franciszek', @LastName=Szczot, @Email='anitaplona@example.org', @Phone='48228312412', @AddressID=487
EXEC addClient @ClientType='I', @FirstName='Michał', @LastName=Ulfik, @Email='rozahapka@example.com', @Phone='48698719594', @AddressID=214
EXEC addClient @ClientType='I', @FirstName='Fabian', @LastName=Frydrychowicz, @Email='wierteleliza@example.net', @Phone='48724897294', @AddressID=441
EXEC addClient @ClientType='I', @FirstName='Blanka', @LastName=Sołtysek, @Email='wojciech42@example.net', @Phone='48885967693', @AddressID=248
EXEC addClient @ClientType='I', @FirstName='Jędrzej', @LastName=Pietryga, @Email='swiatekjeremi@example.net', @Phone='794023766', @AddressID=392
EXEC addClient @ClientType='I', @FirstName='Artur', @LastName=Wasiuk, @Email='trabkaolgierd@example.org', @Phone='48320247097', @AddressID=377
EXEC addClient @ClientType='I', @FirstName='Ewa', @LastName=Kolendo, @Email='lidia03@example.org', @Phone='738713743', @AddressID=286
EXEC addClient @ClientType='I', @FirstName='Marcel', @LastName=Chwalisz, @Email='nela48@example.net', @Phone='223660646', @AddressID=312
EXEC addClient @ClientType='I', @FirstName='Adam', @LastName=Ficoń, @Email='gustaw18@example.org', @Phone='48515550138', @AddressID=455
EXEC addClient @ClientType='I', @FirstName='Konrad', @LastName=Glica, @Email='zgubernat@example.com', @Phone='508507565', @AddressID=298
EXEC addClient @ClientType='I', @FirstName='Hubert', @LastName=Łapacz, @Email='leonard68@example.org', @Phone='48321431944', @AddressID=342
EXEC addClient @ClientType='I', @FirstName='Maks', @LastName=Boś, @Email='wiktorwalentynowicz@example.org', @Phone='48725067724', @AddressID=18
EXEC addClient @ClientType='I', @FirstName='Eryk', @LastName=Bzymek, @Email='marikagosz@example.com', @Phone='692190326', @AddressID=319
EXEC addClient @ClientType='I', @FirstName='Aleksander', @LastName=Graban, @Email='snochnatan@example.net', @Phone='48575862122', @AddressID=295
EXEC addClient @ClientType='I', @FirstName='Kaja', @LastName=Majdak, @Email='holewahubert@example.org', @Phone='48320447851', @AddressID=421
EXEC addClient @ClientType='I', @FirstName='Cezary', @LastName=Serwa, @Email='gwawrzyk@example.net', @Phone='48223518651', @AddressID=351
EXEC addClient @ClientType='I', @FirstName='Borys', @LastName=Trzpil, @Email='konstanty08@example.net', @Phone='501869033', @AddressID=45
EXEC addClient @ClientType='I', @FirstName='Ada', @LastName=Ciuba, @Email='krysikdaniel@example.com', @Phone='48667510601', @AddressID=311
EXEC addClient @ClientType='I', @FirstName='Natan', @LastName=Tłuczek, @Email='mateuszogrodowicz@example.com', @Phone='723333424', @AddressID=462
EXEC addClient @ClientType='I', @FirstName='Marcin', @LastName=Pietrek, @Email='ryszard36@example.com', @Phone='727155912', @AddressID=499
EXEC addClient @ClientType='I', @FirstName='Kaja', @LastName=Pachnik, @Email='korneltaciak@example.com', @Phone='48577222740', @AddressID=394
EXEC addClient @ClientType='I', @FirstName='Janina', @LastName=Kansy, @Email='apiesik@example.org', @Phone='48517237953', @AddressID=17
EXEC addClient @ClientType='I', @FirstName='Konstanty', @LastName=Janc, @Email='marika75@example.net', @Phone='48782676970', @AddressID=109
EXEC addClient @ClientType='I', @FirstName='Adam', @LastName=Lewicz, @Email='czescikjustyna@example.net', @Phone='665473279', @AddressID=433
EXEC addClient @ClientType='I', @FirstName='Justyna', @LastName=Marchlewicz, @Email='pielechkornel@example.org', @Phone='48320793500', @AddressID=57
EXEC addClient @ClientType='I', @FirstName='Olgierd', @LastName=Sieg, @Email='bkaczmar@example.net', @Phone='788168252', @AddressID=326
EXEC addClient @ClientType='I', @FirstName='Kazimierz', @LastName=Buksa, @Email='kwolkowicz@example.com', @Phone='48530154758', @AddressID=260
EXEC addClient @ClientType='I', @FirstName='Angelika', @LastName=Gabryelczyk, @Email='ssleczka@example.org', @Phone='48785832928', @AddressID=376
EXEC addClient @ClientType='I', @FirstName='Tymoteusz', @LastName=Bajak, @Email='llyczek@example.com', @Phone='221702641', @AddressID=410
EXEC addClient @ClientType='I', @FirstName='Marcel', @LastName=Leżoń, @Email='idapawela@example.net', @Phone='48326720574', @AddressID=247
EXEC addClient @ClientType='I', @FirstName='Agnieszka', @LastName=Hanusiak, @Email='mpiejko@example.org', @Phone='783127130', @AddressID=281
EXEC addClient @ClientType='I', @FirstName='Tymon', @LastName=Malewicz, @Email='radoslawidzi@example.com', @Phone='48729670468', @AddressID=418
EXEC addClient @ClientType='I', @FirstName='Arkadiusz', @LastName=Jaroch, @Email='ryszardszmurlo@example.net', @Phone='325663679', @AddressID=44
EXEC addClient @ClientType='I', @FirstName='Rafał', @LastName=Koleśnik, @Email='kornelfabianczyk@example.org', @Phone='48607729522', @AddressID=35
EXEC addClient @ClientType='I', @FirstName='Aniela', @LastName=Chlebda, @Email='fabian25@example.com', @Phone='882713683', @AddressID=323
EXEC addClient @ClientType='I', @FirstName='Sonia', @LastName=Rajda, @Email='bhudzik@example.org', @Phone='48229567672', @AddressID=118
EXEC addClient @ClientType='I', @FirstName='Roksana', @LastName=Jarczyk, @Email='antoniwarczak@example.com', @Phone='48608402904', @AddressID=243
EXEC addClient @ClientType='I', @FirstName='Andrzej', @LastName=Niebudek, @Email='flukas@example.com', @Phone='505935484', @AddressID=158
EXEC addClient @ClientType='I', @FirstName='Marika', @LastName=Jarosiewicz, @Email='iwobruzda@example.com', @Phone='725181826', @AddressID=120
EXEC addClient @ClientType='I', @FirstName='Kornel', @LastName=Warych, @Email='rhynek@example.org', @Phone='531996618', @AddressID=138
EXEC addClient @ClientType='I', @FirstName='Karol', @LastName=Tekiela, @Email='borys31@example.net', @Phone='663301425', @AddressID=227
EXEC addClient @ClientType='I', @FirstName='Malwina', @LastName=Fronia, @Email='nmlot@example.com', @Phone='572033899', @AddressID=500
EXEC addClient @ClientType='I', @FirstName='Maurycy', @LastName=Soczewka, @Email='cyprianfraszczyk@example.com', @Phone='515670479', @AddressID=409
EXEC addClient @ClientType='I', @FirstName='Stefan', @LastName=Śmieszek, @Email='pyrzgaja@example.net', @Phone='48786385600', @AddressID=281
EXEC addClient @ClientType='I', @FirstName='Ksawery', @LastName=Łasak, @Email='krzysztof60@example.org', @Phone='532430853', @AddressID=336
EXEC addClient @ClientType='I', @FirstName='Kajetan', @LastName=Czubaj, @Email='jan74@example.org', @Phone='48738127858', @AddressID=220
EXEC addClient @ClientType='I', @FirstName='Konrad', @LastName=Żuchowicz, @Email='urszula32@example.net', @Phone='48321955000', @AddressID=500
EXEC addClient @ClientType='I', @FirstName='Adrian', @LastName=Toś, @Email='urodakonrad@example.org', @Phone='48572083292', @AddressID=98
EXEC addClient @ClientType='I', @FirstName='Bianka', @LastName=Bździuch, @Email='krystian95@example.org', @Phone='48602201415', @AddressID=306
EXEC addClient @ClientType='I', @FirstName='Justyna', @LastName=Łyjak, @Email='klarawestfal@example.com', @Phone='729315820', @AddressID=200
EXEC addClient @ClientType='I', @FirstName='Konrad', @LastName=Kowara, @Email='natanielfidor@example.net', @Phone='691053966', @AddressID=265
EXEC addClient @ClientType='I', @FirstName='Łukasz', @LastName=Smagała, @Email='kaczkajeremi@example.org', @Phone='784454560', @AddressID=204
EXEC addClient @ClientType='I', @FirstName='Stefan', @LastName=Kamyk, @Email='iskierkarafal@example.net', @Phone='48518507220', @AddressID=226
EXEC addClient @ClientType='I', @FirstName='Marika', @LastName=Szczepan, @Email='eoglaza@example.org', @Phone='797422395', @AddressID=312
EXEC addClient @ClientType='I', @FirstName='Bartek', @LastName=Cader, @Email='leonmarat@example.net', @Phone='782743647', @AddressID=335
EXEC addClient @ClientType='I', @FirstName='Malwina', @LastName=Księżak, @Email='arkadiusz84@example.net', @Phone='48726786043', @AddressID=360
EXEC addClient @ClientType='I', @FirstName='Roksana', @LastName=Fedyk, @Email='przekwasnatan@example.org', @Phone='48721366852', @AddressID=478
EXEC addClient @ClientType='I', @FirstName='Konrad', @LastName=Linek, @Email='suchorarozalia@example.org', @Phone='48575925544', @AddressID=213
EXEC addClient @ClientType='I', @FirstName='Roksana', @LastName=Solnica, @Email='rozalia90@example.com', @Phone='731649518', @AddressID=458
EXEC addClient @ClientType='I', @FirstName='Aniela', @LastName=Krzyżostaniak, @Email='efranc@example.org', @Phone='48608901784', @AddressID=64
EXEC addClient @ClientType='I', @FirstName='Daniel', @LastName=Subocz, @Email='sara55@example.net', @Phone='48795331539', @AddressID=11
EXEC addClient @ClientType='I', @FirstName='Igor', @LastName=Wojtach, @Email='halamacyprian@example.net', @Phone='720392729', @AddressID=230
EXEC addClient @ClientType='I', @FirstName='Dawid', @LastName=Łakota, @Email='kawiakaniela@example.net', @Phone='48883733818', @AddressID=75
EXEC addClient @ClientType='I', @FirstName='Kazimierz', @LastName=Janiga, @Email='hbieniak@example.com', @Phone='791978461', @AddressID=392
EXEC addClient @ClientType='I', @FirstName='Przemysław', @LastName=Plak, @Email='marcinpachowicz@example.com', @Phone='48225961608', @AddressID=40
EXEC addClient @ClientType='I', @FirstName='Natan', @LastName=Osial, @Email='vkrauz@example.net', @Phone='786505714', @AddressID=186
EXEC addClient @ClientType='I', @FirstName='Blanka', @LastName=Smalec, @Email='maks69@example.org', @Phone='48882860452', @AddressID=387
EXEC addClient @ClientType='I', @FirstName='Kornel', @LastName=Góraj, @Email='vwelc@example.com', @Phone='669789288', @AddressID=392
EXEC addClient @ClientType='I', @FirstName='Blanka', @LastName=Strama, @Email='cabalanicole@example.com', @Phone='690616243', @AddressID=480
EXEC addClient @ClientType='I', @FirstName='Adam', @LastName=Kiepas, @Email='wiktorzach@example.com', @Phone='699661444', @AddressID=410
EXEC addClient @ClientType='I', @FirstName='Anna Maria', @LastName=Doliwa, @Email='lkieszek@example.com', @Phone='48604474153', @AddressID=356
EXEC addClient @ClientType='I', @FirstName='Wojciech', @LastName=Węgrzyniak, @Email='vlinka@example.net', @Phone='505193790', @AddressID=255
EXEC addClient @ClientType='I', @FirstName='Nela', @LastName=Sobel, @Email='elizamatyka@example.com', @Phone='48721532339', @AddressID=432
EXEC addClient @ClientType='I', @FirstName='Inga', @LastName=Kiwior, @Email='yjuras@example.org', @Phone='48511980122', @AddressID=8
EXEC addClient @ClientType='I', @FirstName='Jerzy', @LastName=Skała, @Email='albert79@example.org', @Phone='782698089', @AddressID=26
EXEC addClient @ClientType='I', @FirstName='Róża', @LastName=Kosno, @Email='dawid51@example.org', @Phone='48220625212', @AddressID=312
EXEC addClient @ClientType='I', @FirstName='Agnieszka', @LastName=Szołtysik, @Email='wiktorstempel@example.com', @Phone='666765388', @AddressID=15
EXEC addClient @ClientType='I', @FirstName='Kornelia', @LastName=Myrcik, @Email='jozef52@example.com', @Phone='48884471624', @AddressID=352
EXEC addClient @ClientType='I', @FirstName='Fabian', @LastName=Andziak, @Email='ciastekjustyna@example.net', @Phone='509650230', @AddressID=79
EXEC addClient @ClientType='I', @FirstName='Franciszek', @LastName=Łągiewka, @Email='tomaszgradziel@example.org', @Phone='694730358', @AddressID=459
EXEC addClient @ClientType='I', @FirstName='Kacper', @LastName=Ziegert, @Email='igoreckert@example.net', @Phone='606540365', @AddressID=480
EXEC addClient @ClientType='I', @FirstName='Kornel', @LastName=Kandora, @Email='arturoleszko@example.net', @Phone='722487243', @AddressID=28
EXEC addClient @ClientType='I', @FirstName='Józef', @LastName=Basaj, @Email='swrochna@example.org', @Phone='739523087', @AddressID=290
EXEC addClient @ClientType='I', @FirstName='Ida', @LastName=Kus, @Email='marcinradzio@example.net', @Phone='48519805753', @AddressID=340
EXEC addClient @ClientType='I', @FirstName='Leonard', @LastName=Piątkiewicz, @Email='zlaszkiewicz@example.com', @Phone='324877579', @AddressID=231
EXEC addClient @ClientType='I', @FirstName='Józef', @LastName=Koman, @Email='mateuszlesna@example.com', @Phone='48794445206', @AddressID=464
EXEC addClient @ClientType='I', @FirstName='Adam', @LastName=Chojna, @Email='olgabielen@example.org', @Phone='48737021509', @AddressID=7
EXEC addClient @ClientType='I', @FirstName='Cezary', @LastName=Loba, @Email='tadeuszkiedrowicz@example.net', @Phone='789316469', @AddressID=194
EXEC addClient @ClientType='I', @FirstName='Róża', @LastName=Szyda, @Email='julitauliczka@example.org', @Phone='48699650029', @AddressID=327
EXEC addClient @ClientType='I', @FirstName='Julianna', @LastName=Pawlukiewicz, @Email='langiermaks@example.org', @Phone='534370079', @AddressID=102
EXEC addClient @ClientType='I', @FirstName='Maksymilian', @LastName=Mućko, @Email='janinafiutak@example.net', @Phone='48888953243', @AddressID=166
EXEC addClient @ClientType='I', @FirstName='Rozalia', @LastName=Dorawa, @Email='okielbus@example.com', @Phone='575386469', @AddressID=308
EXEC addClient @ClientType='I', @FirstName='Julita', @LastName=Eckert, @Email='golekdariusz@example.org', @Phone='790073474', @AddressID=195
EXEC addClient @ClientType='I', @FirstName='Konstanty', @LastName=Łakota, @Email='aurelialewko@example.net', @Phone='577044244', @AddressID=58
EXEC addClient @ClientType='I', @FirstName='Antoni', @LastName=Pajdak, @Email='marcelgolczyk@example.com', @Phone='532669009', @AddressID=13
EXEC addClient @ClientType='I', @FirstName='Nela', @LastName=Gosek, @Email='rluszczak@example.com', @Phone='325671502', @AddressID=127
EXEC addClient @ClientType='I', @FirstName='Elżbieta', @LastName=Wołoszczuk, @Email='jerzyrajtar@example.net', @Phone='48530783244', @AddressID=288
EXEC addClient @ClientType='I', @FirstName='Aurelia', @LastName=Tecław, @Email='anitamisiuk@example.net', @Phone='48577303169', @AddressID=117
EXEC addClient @ClientType='I', @FirstName='Maurycy', @LastName=Elsner, @Email='borys60@example.org', @Phone='668910178', @AddressID=398
EXEC addClient @ClientType='I', @FirstName='Inga', @LastName=Gaś, @Email='stanislawfabianczyk@example.com', @Phone='48787158768', @AddressID=275
EXEC addClient @ClientType='I', @FirstName='Maurycy', @LastName=Szymocha, @Email='leonardusarek@example.com', @Phone='48601589965', @AddressID=71
EXEC addClient @ClientType='I', @FirstName='Przemysław', @LastName=Oskroba, @Email='hmisiejuk@example.com', @Phone='696531810', @AddressID=191
EXEC addClient @ClientType='I', @FirstName='Marek', @LastName=Grotek, @Email='blazej87@example.net', @Phone='691295071', @AddressID=111
EXEC addClient @ClientType='I', @FirstName='Róża', @LastName=Szajner, @Email='qburnat@example.com', @Phone='538947324', @AddressID=81
EXEC addClient @ClientType='I', @FirstName='Monika', @LastName=Kowalówka, @Email='klausignacy@example.net', @Phone='48883982934', @AddressID=79
EXEC addClient @ClientType='I', @FirstName='Natasza', @LastName=Karpeta, @Email='orzeszekmikolaj@example.org', @Phone='609241567', @AddressID=32
EXEC addClient @ClientType='I', @FirstName='Ewa', @LastName=Cichowlas, @Email='angelika39@example.org', @Phone='327629281', @AddressID=374
EXEC addClient @ClientType='I', @FirstName='Arkadiusz', @LastName=Jarczyk, @Email='wyrwichfabian@example.org', @Phone='48600024870', @AddressID=9
EXEC addClient @ClientType='I', @FirstName='Hubert', @LastName=Wojczuk, @Email='piotr43@example.com', @Phone='696661277', @AddressID=495
EXEC addClient @ClientType='I', @FirstName='Dawid', @LastName=Oleksik, @Email='szczerbiakcyprian@example.com', @Phone='48791600394', @AddressID=402
EXEC addClient @ClientType='I', @FirstName='Albert', @LastName=Stachów, @Email='kalisiakmarcelina@example.net', @Phone='720466209', @AddressID=442
EXEC addClient @ClientType='I', @FirstName='Dagmara', @LastName=Jop, @Email='spiekara@example.net', @Phone='48783462671', @AddressID=361
EXEC addClient @ClientType='I', @FirstName='Maurycy', @LastName=Ciochoń, @Email='ignacy03@example.com', @Phone='48600442020', @AddressID=72
EXEC addClient @ClientType='I', @FirstName='Aniela', @LastName=Litwa, @Email='rszlek@example.com', @Phone='48604071098', @AddressID=133
EXEC addClient @ClientType='I', @FirstName='Norbert', @LastName=Grzela, @Email='tolabrygola@example.org', @Phone='48503507863', @AddressID=53
EXEC addClient @ClientType='I', @FirstName='Michał', @LastName=Kajstura, @Email='arzucidlo@example.org', @Phone='48739688051', @AddressID=260
EXEC addClient @ClientType='I', @FirstName='Roksana', @LastName=Smagacz, @Email='ksawerypodsiadla@example.com', @Phone='517072633', @AddressID=174
EXEC addClient @ClientType='I', @FirstName='Roksana', @LastName=Andrejczuk, @Email='bpietraszkiewicz@example.com', @Phone='48573089361', @AddressID=49
EXEC addClient @ClientType='I', @FirstName='Sandra', @LastName=Hermanowicz, @Email='dpych@example.net', @Phone='661651634', @AddressID=265
EXEC addClient @ClientType='I', @FirstName='Sandra', @LastName=Stwora, @Email='bieszkeiwo@example.org', @Phone='48325548412', @AddressID=332
EXEC addClient @ClientType='I', @FirstName='Ada', @LastName=Pacholczak, @Email='nikodem82@example.org', @Phone='48666525701', @AddressID=280
EXEC addClient @ClientType='I', @FirstName='Karina', @LastName=Skrobot, @Email='spacyga@example.com', @Phone='735706333', @AddressID=119
EXEC addClient @ClientType='I', @FirstName='Filip', @LastName=Szpala, @Email='mariusztyniec@example.net', @Phone='48536191443', @AddressID=270
EXEC addClient @ClientType='I', @FirstName='Oskar', @LastName=Sładek, @Email='iwylupek@example.com', @Phone='48512125473', @AddressID=360
EXEC addClient @ClientType='I', @FirstName='Antoni', @LastName=Judek, @Email='erykmalys@example.com', @Phone='48783982899', @AddressID=450
EXEC addClient @ClientType='I', @FirstName='Juliusz', @LastName=Wawrzynowicz, @Email='pawelczesak@example.net', @Phone='48883271939', @AddressID=471
EXEC addClient @ClientType='I', @FirstName='Marika', @LastName=Chabior, @Email='apolonia66@example.org', @Phone='48607779575', @AddressID=500
EXEC addClient @ClientType='I', @FirstName='Wiktor', @LastName=Jankowicz, @Email='lulrych@example.net', @Phone='48228589823', @AddressID=86
EXEC addClient @ClientType='I', @FirstName='Borys', @LastName=Pielech, @Email='swigonmarianna@example.com', @Phone='323868343', @AddressID=419
EXEC addClient @ClientType='I', @FirstName='Roksana', @LastName=Szwaja, @Email='kopytkoaurelia@example.org', @Phone='224833555', @AddressID=470
EXEC addClient @ClientType='I', @FirstName='Bartek', @LastName=Gosek, @Email='rozalia21@example.net', @Phone='571115165', @AddressID=123
EXEC addClient @ClientType='I', @FirstName='Mieszko', @LastName=Boryczko, @Email='jklyszcz@example.org', @Phone='48323960218', @AddressID=480
EXEC addClient @ClientType='I', @FirstName='Ernest', @LastName=Chachaj, @Email='tarachkacper@example.org', @Phone='738076893', @AddressID=385
EXEC addClient @ClientType='I', @FirstName='Ada', @LastName=Piwek, @Email='jeremi08@example.net', @Phone='48579024955', @AddressID=109
EXEC addClient @ClientType='I', @FirstName='Kalina', @LastName=Pesta, @Email='krzyzostaniakmikolaj@example.com', @Phone='227392218', @AddressID=226
EXEC addClient @ClientType='I', @FirstName='Tobiasz', @LastName=Białach, @Email='apoloniajewula@example.org', @Phone='48692538336', @AddressID=429
EXEC addClient @ClientType='I', @FirstName='Marika', @LastName=Fołta, @Email='juliuszzuziak@example.net', @Phone='690632205', @AddressID=257
EXEC addClient @ClientType='I', @FirstName='Sonia', @LastName=Mizia, @Email='bartekkonat@example.com', @Phone='697074172', @AddressID=465
EXEC addClient @ClientType='I', @FirstName='Kazimierz', @LastName=Melka, @Email='jedrzejkiryluk@example.net', @Phone='48728828093', @AddressID=144
EXEC addClient @ClientType='I', @FirstName='Leonard', @LastName=Tekiela, @Email='witold13@example.com', @Phone='48602275084', @AddressID=221
EXEC addClient @ClientType='I', @FirstName='Piotr', @LastName=Wendt, @Email='pdamps@example.net', @Phone='504198500', @AddressID=435
EXEC addClient @ClientType='I', @FirstName='Damian', @LastName=Pancerz, @Email='szpalaartur@example.net', @Phone='48668304871', @AddressID=80
EXEC addClient @ClientType='I', @FirstName='Olgierd', @LastName=Piechna, @Email='ceynowakamila@example.net', @Phone='48509644302', @AddressID=482
EXEC addClient @ClientType='I', @FirstName='Blanka', @LastName=Strządała, @Email='zkurzak@example.net', @Phone='48799958458', @AddressID=307
EXEC addClient @ClientType='I', @FirstName='Lidia', @LastName=Ruszczak, @Email='kajetanengler@example.com', @Phone='48882429473', @AddressID=360
EXEC addClient @ClientType='I', @FirstName='Albert', @LastName=Grzegorzak, @Email='kempnytola@example.net', @Phone='48516535470', @AddressID=220
EXEC addClient @ClientType='I', @FirstName='Szymon', @LastName=Zioła, @Email='fabianchlebek@example.net', @Phone='531837327', @AddressID=419
EXEC addClient @ClientType='I', @FirstName='Bartek', @LastName=Piotrak, @Email='elizamilka@example.com', @Phone='515581040', @AddressID=484
EXEC addClient @ClientType='I', @FirstName='Dominik', @LastName=Frycz, @Email='danielpuch@example.org', @Phone='48796231073', @AddressID=175
EXEC addClient @ClientType='I', @FirstName='Patryk', @LastName=Zbiciak, @Email='drobnikwiktor@example.com', @Phone='880292390', @AddressID=163
EXEC addClient @ClientType='I', @FirstName='Tola', @LastName=Kobza, @Email='sylwiafron@example.org', @Phone='500978125', @AddressID=475
EXEC addClient @ClientType='I', @FirstName='Tadeusz', @LastName=Thomas, @Email='julita13@example.net', @Phone='510378520', @AddressID=51
EXEC addClient @ClientType='I', @FirstName='Marika', @LastName=Konieczek, @Email='rozalia56@example.net', @Phone='48799002855', @AddressID=403
EXEC addClient @ClientType='I', @FirstName='Fryderyk', @LastName=Baś, @Email='liwia77@example.org', @Phone='48734901302', @AddressID=70
EXEC addClient @ClientType='I', @FirstName='Jerzy', @LastName=Drabczyk, @Email='mrotekdorota@example.com', @Phone='572945249', @AddressID=371
EXEC addClient @ClientType='I', @FirstName='Maurycy', @LastName=Obst, @Email='chojaknorbert@example.net', @Phone='48725782294', @AddressID=247
EXEC addClient @ClientType='I', @FirstName='Tymoteusz', @LastName=Pacholik, @Email='konrad14@example.net', @Phone='661489579', @AddressID=151
EXEC addClient @ClientType='I', @FirstName='Bartek', @LastName=Chaber, @Email='emil15@example.net', @Phone='48228633798', @AddressID=141
EXEC addClient @ClientType='I', @FirstName='Krystian', @LastName=Harasimiuk, @Email='mblazejczak@example.org', @Phone='325072660', @AddressID=317
EXEC addClient @ClientType='I', @FirstName='Tola', @LastName=Durczok, @Email='fabian57@example.com', @Phone='48502125845', @AddressID=378
EXEC addClient @ClientType='I', @FirstName='Marcelina', @LastName=Poczta, @Email='andrzejostafin@example.org', @Phone='48783967358', @AddressID=347
EXEC addClient @ClientType='I', @FirstName='Przemysław', @LastName=Portka, @Email='kiepuratymon@example.org', @Phone='48220217393', @AddressID=108
EXEC addClient @ClientType='I', @FirstName='Julian', @LastName=Cimoch, @Email='leonard35@example.net', @Phone='48880073797', @AddressID=367
EXEC addClient @ClientType='I', @FirstName='Iwo', @LastName=Boksa, @Email='smaltola@example.org', @Phone='791361065', @AddressID=2
EXEC addClient @ClientType='I', @FirstName='Stanisław', @LastName=Hewelt, @Email='kklinger@example.org', @Phone='48227687622', @AddressID=470
EXEC addClient @ClientType='I', @FirstName='Miłosz', @LastName=Matejczyk, @Email='kornel16@example.com', @Phone='606165802', @AddressID=53
EXEC addClient @ClientType='I', @FirstName='Oliwier', @LastName=Wacławczyk, @Email='bkrzyzostaniak@example.org', @Phone='48692159824', @AddressID=152
EXEC addClient @ClientType='I', @FirstName='Maurycy', @LastName=Foit, @Email='pwoloch@example.com', @Phone='787755231', @AddressID=73
EXEC addClient @ClientType='I', @FirstName='Krystyna', @LastName=Robaszkiewicz, @Email='piotr57@example.org', @Phone='696161710', @AddressID=480
EXEC addClient @ClientType='I', @FirstName='Róża', @LastName=Grzech, @Email='jankostro@example.com', @Phone='48784981448', @AddressID=163
EXEC addClient @ClientType='I', @FirstName='Krystyna', @LastName=Woda, @Email='nitkiewiczbartek@example.org', @Phone='48328544948', @AddressID=2
EXEC addClient @ClientType='I', @FirstName='Konstanty', @LastName=Karpik, @Email='gromalaaniela@example.net', @Phone='782724718', @AddressID=21
EXEC addClient @ClientType='I', @FirstName='Gaja', @LastName=Materek, @Email='ybachanek@example.org', @Phone='785671098', @AddressID=441
EXEC addClient @ClientType='I', @FirstName='Marcel', @LastName=Famuła, @Email='burzawaadrianna@example.com', @Phone='888625129', @AddressID=382
EXEC addClient @ClientType='I', @FirstName='Malwina', @LastName=Sprawka, @Email='kruszkamaksymilian@example.com', @Phone='48721995151', @AddressID=443
EXEC addClient @ClientType='I', @FirstName='Tymon', @LastName=Rezmer, @Email='milosz39@example.com', @Phone='600288737', @AddressID=288
EXEC addClient @ClientType='I', @FirstName='Grzegorz', @LastName=Koss, @Email='ada40@example.com', @Phone='48699151483', @AddressID=395
EXEC addClient @ClientType='I', @FirstName='Eliza', @LastName=Kubowicz, @Email='jakub39@example.com', @Phone='48731901860', @AddressID=462
EXEC addClient @ClientType='I', @FirstName='Natasza', @LastName=Gubernat, @Email='mintaignacy@example.com', @Phone='48321256726', @AddressID=248
EXEC addClient @ClientType='I', @FirstName='Łukasz', @LastName=Garncarek, @Email='adrianna08@example.org', @Phone='48669294210', @AddressID=132
EXEC addClient @ClientType='I', @FirstName='Olgierd', @LastName=Balik, @Email='franciszek76@example.org', @Phone='576153879', @AddressID=460
EXEC addClient @ClientType='I', @FirstName='Oskar', @LastName=Lenda, @Email='sandra69@example.com', @Phone='48532856062', @AddressID=426
EXEC addClient @ClientType='I', @FirstName='Maks', @LastName=Andruszko, @Email='aleksanderturlej@example.net', @Phone='48727814997', @AddressID=204
EXEC addClient @ClientType='I', @FirstName='Sebastian', @LastName=Wawak, @Email='elzbietapawlos@example.org', @Phone='48519726523', @AddressID=196
EXEC addClient @ClientType='I', @FirstName='Adrian', @LastName=Bittner, @Email='antoni29@example.net', @Phone='48535434909', @AddressID=244
EXEC addClient @ClientType='I', @FirstName='Oskar', @LastName=Symonowicz, @Email='nikodembik@example.com', @Phone='48323258301', @AddressID=469
EXEC addClient @ClientType='I', @FirstName='Kamil', @LastName=Welc, @Email='sieczkonatan@example.com', @Phone='48690377868', @AddressID=467
EXEC addClient @ClientType='I', @FirstName='Gustaw', @LastName=Gmur, @Email='kleinakonstanty@example.org', @Phone='668605712', @AddressID=481
EXEC addClient @ClientType='I', @FirstName='Fryderyk', @LastName=Praczyk, @Email='marek98@example.net', @Phone='727413018', @AddressID=498
EXEC addClient @ClientType='I', @FirstName='Julianna', @LastName=Deluga, @Email='tzakiewicz@example.org', @Phone='48606777988', @AddressID=413