EXEC addProductToMenu 'Espresso', 3, 19;
EXEC addProductToMenu 'Cappuccino', 3, 35;
EXEC addProductToMenu 'Latte', 3, 24;
EXEC addProductToMenu 'Macchiato', 3, 27;
EXEC addProductToMenu 'Americano', 3, 26;
EXEC addProductToMenu 'Mocha', 3, 24;
EXEC addProductToMenu 'Cortado', 3, 27;
EXEC addProductToMenu 'Flat white', 3, 19;
EXEC addProductToMenu 'Affogato', 3, 25;
EXEC addProductToMenu 'Café au lait', 3, 16;
EXEC addProductToMenu 'Café bombón', 3, 16;
EXEC addProductToMenu 'Café mélange', 3, 21;
EXEC addProductToMenu 'Café mocha', 3, 19;
EXEC addProductToMenu 'Café zorro', 3, 18;
EXEC addProductToMenu 'Café Cubano', 3, 17;
EXEC addProductToMenu 'Café con leche', 3, 35;
EXEC addProductToMenu 'Café crema', 3, 30;
EXEC addProductToMenu 'Café de olla', 3, 17;
EXEC addProductToMenu 'Café de pico', 3, 35;
EXEC addProductToMenu 'Café del mar', 3, 16;
EXEC addProductToMenu 'Café gourmand', 3, 35;
EXEC addProductToMenu 'Café irlandés', 3, 28;
EXEC addProductToMenu 'Café marrón', 3, 35;
EXEC addProductToMenu 'Café mélange', 3, 35;
EXEC addProductToMenu 'Black tea', 3, 15;
EXEC addProductToMenu 'Green tea', 3, 28;
EXEC addProductToMenu 'Oolong tea', 3, 17;
EXEC addProductToMenu 'White tea', 3, 21;
EXEC addProductToMenu 'Yellow tea', 3, 15;
EXEC addProductToMenu 'Pu-erh tea', 3, 23;
EXEC addProductToMenu 'Herbal tea', 3, 14;
EXEC addProductToMenu 'Rooibos tea', 3, 24;
EXEC addProductToMenu 'Mate tea', 3, 22;
EXEC addProductToMenu 'Chai tea', 3, 19;
EXEC addProductToMenu 'Matcha tea', 3, 34;
EXEC addProductToMenu 'Kombucha tea', 3, 25;
EXEC addProductToMenu 'Honeybush tea', 3, 34;
EXEC addProductToMenu 'Apple juice', 3, 12;
EXEC addProductToMenu 'Orange juice', 3, 12;
EXEC addProductToMenu 'Grapefruit juice', 3, 31;
EXEC addProductToMenu 'Pineapple juice', 3, 31;
EXEC addProductToMenu 'Lemon juice', 3, 22;
EXEC addProductToMenu 'Lime juice', 3, 15;
EXEC addProductToMenu 'Grape juice', 3, 28;
EXEC addProductToMenu 'Pomegranate juice', 3, 21;
EXEC addProductToMenu 'Carrot juice', 3, 27;
EXEC addProductToMenu 'Tomato juice', 3, 35;
EXEC addProductToMenu 'Cranberry juice', 3, 14;
EXEC addProductToMenu 'Strawberry juice', 3, 33;
EXEC addProductToMenu 'Raspberry juice', 3, 23;
EXEC addProductToMenu 'Blueberry juice', 3, 15;
EXEC addProductToMenu 'Coca-Cola', 3, 22;
EXEC addProductToMenu 'Pepsi', 3, 21;
EXEC addProductToMenu 'Dr Pepper', 3, 16;
EXEC addProductToMenu 'Mountain Dew', 3, 14;
EXEC addProductToMenu 'Sprite', 3, 19;
EXEC addProductToMenu '7 Up', 3, 15;
EXEC addProductToMenu 'Fanta', 3, 27;
EXEC addProductToMenu 'Sierra Mist', 3, 24;
EXEC addProductToMenu 'Diet Coke', 3, 16;
EXEC addProductToMenu 'Diet Pepsi', 3, 16;
EXEC addProductToMenu 'Diet Dr Pepper', 3, 29;
EXEC addProductToMenu 'Diet Mountain Dew', 3, 13;
EXEC addProductToMenu 'Diet Sprite', 3, 32;
EXEC addProductToMenu 'Diet 7 Up', 3, 27;
EXEC addProductToMenu 'Diet Fanta', 3, 31;
EXEC addProductToMenu 'Diet Sierra Mist', 3, 20;
EXEC addProductToMenu 'Coke Zero', 3, 25;
EXEC addProductToMenu 'Chicken soup', 3, 27;
EXEC addProductToMenu 'Beef soup', 3, 16;
EXEC addProductToMenu 'Vegetable soup', 3, 29;
EXEC addProductToMenu 'Tomato soup', 3, 20;
EXEC addProductToMenu 'Potato soup', 3, 19;
EXEC addProductToMenu 'Lentil soup', 3, 12;
EXEC addProductToMenu 'Split pea soup', 3, 20;
EXEC addProductToMenu 'Minestrone soup', 3, 17;
EXEC addProductToMenu 'Clam chowder', 3, 33;
EXEC addProductToMenu 'Corn chowder', 3, 20;
EXEC addProductToMenu 'French onion soup', 3, 26;
EXEC addProductToMenu 'Chicken noodle soup', 3, 28;
EXEC addProductToMenu 'Chicken and rice soup', 3, 17;
EXEC addProductToMenu 'Chicken and dumplings', 3, 23;
EXEC addProductToMenu 'Chicken and wild rice soup', 3, 18;
EXEC addProductToMenu 'Chicken tortilla soup', 3, 20;
EXEC addProductToMenu 'Chicken and corn chowder', 3, 21;
EXEC addProductToMenu 'Chicken and broccoli soup', 3, 18;
EXEC addProductToMenu 'Chicken and mushroom soup', 3, 32;
EXEC addProductToMenu 'Chicken and barley soup', 3, 17;
EXEC addProductToMenu 'Caesar salad', 3, 26;
EXEC addProductToMenu 'Greek salad', 3, 16;
EXEC addProductToMenu 'Tossed salad', 3, 23;
EXEC addProductToMenu 'Cobb salad', 3, 30;
EXEC addProductToMenu 'Caprese salad', 3, 21;
EXEC addProductToMenu 'Garden salad', 3, 12;
EXEC addProductToMenu 'Chef salad', 3, 13;
EXEC addProductToMenu 'Antipasto salad', 3, 12;
EXEC addProductToMenu 'Spinach salad', 3, 28;
EXEC addProductToMenu 'Fruit salad', 3, 23;
EXEC addProductToMenu 'Potato salad', 3, 27;
EXEC addProductToMenu 'Macaroni salad', 3, 16;
EXEC addProductToMenu 'Cole slaw', 3, 25;
EXEC addProductToMenu 'Beet salad', 3, 15;
EXEC addProductToMenu 'Cucumber salad', 3, 20;
EXEC addProductToMenu 'Tomato salad', 3, 23;
EXEC addProductToMenu 'Avocado salad', 3, 32;
EXEC addProductToMenu 'Asparagus salad', 3, 29;
EXEC addProductToMenu 'Artichoke salad', 3, 25;
EXEC addProductToMenu 'Broccoli salad', 3, 29;
EXEC addProductToMenu 'Carrot salad', 3, 13;
EXEC addProductToMenu 'Corn salad', 3, 17;
EXEC addProductToMenu 'Guacamole', 3, 25;
EXEC addProductToMenu 'Salsa', 3, 18;
EXEC addProductToMenu 'Hummus', 3, 34;
EXEC addProductToMenu 'Tzatziki', 3, 15;
EXEC addProductToMenu 'Dip', 3, 35;
EXEC addProductToMenu 'Deviled eggs', 3, 35;
EXEC addProductToMenu 'Fried pickles', 3, 16;
EXEC addProductToMenu 'Fried green tomatoes', 3, 34;
EXEC addProductToMenu 'Fried okra', 3, 21;
EXEC addProductToMenu 'Fried mushrooms', 3, 30;
EXEC addProductToMenu 'Fried zucchini', 3, 28;
EXEC addProductToMenu 'Fried calamari', 3, 18;
EXEC addProductToMenu 'Fried mozzarella sticks', 3, 16;
EXEC addProductToMenu 'Fried onion rings', 3, 31;
EXEC addProductToMenu 'Fried potato skins', 3, 21;
EXEC addProductToMenu 'Fried ravioli', 3, 17;
EXEC addProductToMenu 'Baked brie', 3, 15;
EXEC addProductToMenu 'Baked clams', 3, 33;
EXEC addProductToMenu 'Baked crab dip', 3, 34;
EXEC addProductToMenu 'Baked oysters', 3, 24;
EXEC addProductToMenu 'Baked stuffed mushrooms', 3, 20;
EXEC addProductToMenu 'Baked stuffed shrimp', 3, 19;
EXEC addProductToMenu 'Baked stuffed clams', 3, 18;
EXEC addProductToMenu 'Baked stuffed artichokes', 3, 20;
EXEC addProductToMenu 'Baked stuffed zucchini', 3, 25;
EXEC addProductToMenu 'Baked stuffed peppers', 3, 32;
EXEC addProductToMenu 'Baked stuffed tomatoes', 3, 24;
EXEC addProductToMenu 'Baked stuffed potatoes', 3, 31;
EXEC addProductToMenu 'Baked stuffed squash', 3, 31;
EXEC addProductToMenu 'Baked stuffed eggplant', 3, 34;
EXEC addProductToMenu 'Baked stuffed mushrooms', 3, 13;
EXEC addProductToMenu 'Baked stuffed shrimp', 3, 14;
EXEC addProductToMenu 'Vegetable soup', 3, 16;
EXEC addProductToMenu 'Vegetable lasagna', 3, 14;
EXEC addProductToMenu 'Vegetable stir fry', 3, 31;
EXEC addProductToMenu 'Vegetable curry', 3, 16;
EXEC addProductToMenu 'Vegetable stew', 3, 35;
EXEC addProductToMenu 'Vegetable chili', 3, 15;
EXEC addProductToMenu 'Fish', 3, 34;
EXEC addProductToMenu 'Fish roll', 3, 14;
EXEC addProductToMenu 'Fish stick', 3, 31;
EXEC addProductToMenu 'Fish sandwich', 3, 28;
EXEC addProductToMenu 'Fish sandwich roll', 3, 24;
EXEC addProductToMenu 'Fish sandwich stick', 3, 19;
EXEC addProductToMenu 'Fish sandwich bun', 3, 23;
EXEC addProductToMenu 'Beef stew with dumplings', 3, 34;
EXEC addProductToMenu 'Beef stew with potatoes', 3, 33;
EXEC addProductToMenu 'Beef stew with carrots', 3, 27;
EXEC addProductToMenu 'Beef stew with mushrooms', 3, 29;
EXEC addProductToMenu 'Beef stew with onions', 3, 26;
EXEC addProductToMenu 'Beef stew with celery', 3, 29;
EXEC addProductToMenu 'Beef stew with tomatoes', 3, 29;
EXEC addProductToMenu 'Beef stew with cabbage', 3, 27;
EXEC addProductToMenu 'Pasta with meatballs', 3, 20;
EXEC addProductToMenu 'Pasta with sausage', 3, 21;
EXEC addProductToMenu 'Pasta with chicken', 3, 27;
EXEC addProductToMenu 'Pasta with shrimp', 3, 22;
EXEC addProductToMenu 'Pasta with clams', 3, 27;
EXEC addProductToMenu 'Pasta with mussels', 3, 25;
EXEC addProductToMenu 'Pasta with scallops', 3, 19;
EXEC addProductToMenu 'Pasta with lobster', 3, 23;
EXEC addProductToMenu 'Pasta with crab', 3, 35;
EXEC addProductToMenu 'Pasta with salmon', 3, 24;
EXEC addProductToMenu 'Pasta with tuna', 3, 16;
EXEC addProductToMenu 'Pasta with eggplant', 3, 14;
EXEC addProductToMenu 'Pasta with zucchini', 3, 20;
EXEC addProductToMenu 'Pasta with mushrooms', 3, 16;
EXEC addProductToMenu 'Pasta with onions', 3, 32;
EXEC addProductToMenu 'Pasta with tomatoes', 3, 19;
EXEC addProductToMenu 'Pasta with spinach', 3, 12;
EXEC addProductToMenu 'Pasta with broccoli', 3, 30;
EXEC addProductToMenu 'Pasta with cauliflower', 3, 33;
EXEC addProductToMenu 'Chicken casserole', 3, 25;
EXEC addProductToMenu 'Beef casserole', 3, 26;
EXEC addProductToMenu 'Vegetable casserole', 3, 24;
EXEC addProductToMenu 'Angel food cake', 3, 29;
EXEC addProductToMenu 'Banana cake', 3, 25;
EXEC addProductToMenu 'Black forest cake', 3, 15;
EXEC addProductToMenu 'Boston cream cake', 3, 19;
EXEC addProductToMenu 'Bundt cake', 3, 17;
EXEC addProductToMenu 'Carrot cake', 3, 16;
EXEC addProductToMenu 'Cheesecake', 3, 23;
EXEC addProductToMenu 'Chocolate cake', 3, 18;
EXEC addProductToMenu 'Coffee cake', 3, 35;
EXEC addProductToMenu 'Coconut cake', 3, 18;
EXEC addProductToMenu 'Vanilla ice cream', 3, 15;
EXEC addProductToMenu 'Chocolate ice cream', 3, 14;
EXEC addProductToMenu 'Strawberry ice cream', 3, 29;
EXEC addProductToMenu 'Mint chocolate chip ice cream', 3, 34;
EXEC addProductToMenu 'Pistachio ice cream', 3, 16;
EXEC addProductToMenu 'Rocky road ice cream', 3, 16;
EXEC addProductToMenu 'Butter pecan ice cream', 3, 29;
EXEC addProductToMenu 'Moose tracks ice cream', 3, 17;
EXEC addProductToMenu 'Cookies and cream ice cream', 3, 32;
EXEC addProductToMenu 'Chocolate chip cookie dough ice cream', 3, 35;
EXEC addProductToMenu 'Chocolate peanut butter ice cream', 3, 32;
EXEC addProductToMenu 'Chocolate chip ice cream', 3, 21;
EXEC addProductToMenu 'Mint chocolate chip ice cream', 3, 27;
EXEC addProductToMenu 'Pistachio ice cream', 3, 20;
EXEC addProductToMenu 'Rocky road ice cream', 3, 17;
EXEC addProductToMenu 'Butter pecan ice cream', 3, 19;
EXEC addProductToMenu 'Moose tracks ice cream', 3, 16;
EXEC addProductToMenu 'Apple', 3, 22;
EXEC addProductToMenu 'Apricot', 3, 34;
EXEC addProductToMenu 'Avocado', 3, 23;
EXEC addProductToMenu 'Banana', 3, 12;
EXEC addProductToMenu 'Blackberry', 3, 28;
EXEC addProductToMenu 'Blueberry', 3, 16;
EXEC addProductToMenu 'Cherry', 3, 12;
EXEC addProductToMenu 'Coconut', 3, 31;
EXEC addProductToMenu 'Cranberry', 3, 26;
EXEC addProductToMenu 'Date', 3, 31;
EXEC addProductToMenu 'Fig', 3, 29;
EXEC addProductToMenu 'Grape', 3, 26;
EXEC addProductToMenu 'Grapefruit', 3, 25;
EXEC addProductToMenu 'Guava', 3, 24;
EXEC addProductToMenu 'Kiwi', 3, 21;
EXEC addProductToMenu 'Lemon', 3, 14;
EXEC addProductToMenu 'Lime', 3, 14;
EXEC addProductToMenu 'Mango', 3, 20;
EXEC addProductToMenu 'Melon', 3, 33;
EXEC addProductToMenu 'Orange', 3, 13;
EXEC addProductToMenu 'Apple pudding', 3, 32;
EXEC addProductToMenu 'Banana pudding', 3, 29;
EXEC addProductToMenu 'Chocolate pudding', 3, 35;
EXEC addProductToMenu 'Coconut pudding', 3, 19;
EXEC addProductToMenu 'Lemon pudding', 3, 21;
EXEC addProductToMenu 'Peach pudding', 3, 18;
EXEC addProductToMenu 'Pumpkin pudding', 3, 21;
EXEC addProductToMenu 'Rice pudding', 3, 35;
EXEC addProductToMenu 'Strawberry pudding', 3, 26;
EXEC addProductToMenu 'Vanilla pudding', 3, 13;
EXEC addProductToMenu 'Apple custard', 3, 14;
EXEC addProductToMenu 'Banana custard', 3, 26;
EXEC addProductToMenu 'Chocolate custard', 3, 33;
EXEC addProductToMenu 'Coconut custard', 3, 13;
EXEC addProductToMenu 'Lemon custard', 3, 23;
EXEC addProductToMenu 'Peach custard', 3, 16;
EXEC addProductToMenu 'American cheese', 3, 28;
EXEC addProductToMenu 'Cheddar cheese', 3, 32;
EXEC addProductToMenu 'Swiss cheese', 3, 35;
EXEC addProductToMenu 'Mozzarella cheese', 3, 25;
EXEC addProductToMenu 'Provolone cheese', 3, 18;
EXEC addProductToMenu 'Pepper jack cheese', 3, 20;
EXEC addProductToMenu 'Gouda cheese', 3, 20;
EXEC addProductToMenu 'Brie cheese', 3, 25;
EXEC addProductToMenu 'Gruyere cheese', 3, 16;
EXEC addProductToMenu 'Parmesan cheese', 3, 24;
EXEC addProductToMenu 'Romano cheese', 3, 21;
EXEC addProductToMenu 'Asiago cheese', 3, 23;
EXEC addProductToMenu 'Feta cheese', 3, 35;
EXEC addProductToMenu 'Goat cheese', 3, 35;
EXEC addProductToMenu 'Muenster cheese', 3, 25;
EXEC addProductToMenu 'Bleu cheese', 3, 23;
EXEC addProductToMenu 'Boursin cheese', 3, 26;
EXEC addProductToMenu 'Burrata cheese', 3, 23;
EXEC addProductToMenu 'Alfredo sauce', 3, 25;
EXEC addProductToMenu 'Bechamel sauce', 3, 24;
EXEC addProductToMenu 'Béarnaise sauce', 3, 18;
EXEC addProductToMenu 'Bisque sauce', 3, 20;
EXEC addProductToMenu 'Brown sauce', 3, 14;
EXEC addProductToMenu 'Caper sauce', 3, 31;
EXEC addProductToMenu 'Caramel sauce', 3, 15;
EXEC addProductToMenu 'Chimichurri sauce', 3, 13;
EXEC addProductToMenu 'Chutney sauce', 3, 34;
EXEC addProductToMenu 'Cocktail sauce', 3, 24;
EXEC addProductToMenu 'Curry sauce', 3, 32;
EXEC addProductToMenu 'Dijon sauce', 3, 34;
EXEC addProductToMenu 'Dressing sauce', 3, 22;
EXEC addProductToMenu 'Allspice', 3, 27;
EXEC addProductToMenu 'Anise', 3, 34;
EXEC addProductToMenu 'Basil', 3, 35;
EXEC addProductToMenu 'Bay leaf', 3, 12;
EXEC addProductToMenu 'Caraway', 3, 34;
EXEC addProductToMenu 'Cardamom', 3, 21;
EXEC addProductToMenu 'Cayenne', 3, 17;
EXEC addProductToMenu 'Celery seed', 3, 20;
EXEC addProductToMenu 'Chili', 3, 30;
EXEC addProductToMenu 'Cinnamon', 3, 23;
EXEC addProductToMenu 'Cloves', 3, 14;
EXEC addProductToMenu 'Coriander', 3, 29;
EXEC addProductToMenu 'Cumin', 3, 14;
EXEC addProductToMenu 'Curry', 3, 31;
EXEC addProductToMenu 'Grilled salmon with a lemon butter sauce', 3, 31;
EXEC addProductToMenu 'Pan-seared scallops with a white wine sauce', 3, 20;
EXEC addProductToMenu 'Shrimp scampi served over pasta', 3, 25;
EXEC addProductToMenu 'Crab cakes with a remoulade sauce', 3, 27;
EXEC addProductToMenu 'Lobster tail with drawn butter', 3, 14;
EXEC addProductToMenu 'Tuna tartare with avocado and soy sauce', 3, 24;
EXEC addProductToMenu 'Oysters Rockefeller (oysters baked with a spinach and butter sauce)', 3, 25;
EXEC addProductToMenu 'Clam chowder (a creamy soup made with clams)', 3, 25;
EXEC addProductToMenu 'Calamari fritti (deep-fried squid)', 3, 14;
EXEC addProductToMenu 'Grilled octopus with a citrus marinade', 3, 19;
EXEC addProductToMenu 'Fish and chips (battered and fried fish served with French fries)', 3, 32;
EXEC addProductToMenu 'Cioppino (a seafood stew made with a variety of fish and shellfish)', 3, 26;
EXEC addProductToMenu 'Baguette', 3, 31;
EXEC addProductToMenu 'Brioche', 3, 25;
EXEC addProductToMenu 'Bread', 3, 19;
EXEC addProductToMenu 'Breadstick', 3, 12;
EXEC addProductToMenu 'Bun', 3, 33;
EXEC addProductToMenu 'Butter', 3, 14;
EXEC addProductToMenu 'Butter roll', 3, 16;
EXEC addProductToMenu 'Biscuit', 3, 21;
EXEC addProductToMenu 'Biscotti', 3, 28;
EXEC addProductToMenu 'Biscuit roll', 3, 24;
EXEC addProductToMenu 'Biscuit stick', 3, 12;
EXEC addProductToMenu 'Biscuit sandwich', 3, 25;
EXEC addProductToMenu 'Biscuit sandwich roll', 3, 25;
EXEC addProductToMenu 'Biscuit sandwich stick', 3, 20;
EXEC addProductToMenu 'Biscuit sandwich bun', 3, 27;
EXEC addProductToMenu 'Cookie', 3, 28;
EXEC addProductToMenu 'Cookie roll', 3, 12;
EXEC addProductToMenu 'Cookie stick', 3, 18;
EXEC addProductToMenu 'Cookie sandwich', 3, 25;
EXEC addProductToMenu 'Cookie sandwich roll', 3, 21;
EXEC addProductToMenu 'Cookie sandwich stick', 3, 29;
EXEC addProductToMenu 'Cookie sandwich bun', 3, 14;
EXEC addProductToMenu 'Cereal', 3, 35;
EXEC addProductToMenu 'Cereal roll', 3, 21;
EXEC addProductToMenu 'Cereal stick', 3, 16;
EXEC addProductToMenu 'Cereal sandwich', 3, 24;
EXEC addProductToMenu 'Cereal sandwich roll', 3, 31;
EXEC addProductToMenu 'Cereal sandwich stick', 3, 12;
EXEC addProductToMenu 'Almond', 3, 23;
EXEC addProductToMenu 'Cashew', 3, 23;
EXEC addProductToMenu 'Chestnut', 3, 12;
EXEC addProductToMenu 'Coconut', 3, 25;
EXEC addProductToMenu 'Hazelnut', 3, 26;
EXEC addProductToMenu 'Macadamia', 3, 18;
EXEC addProductToMenu 'Peanut', 3, 14;
EXEC addProductToMenu 'Pecan', 3, 12;
EXEC addProductToMenu 'Pistachio', 3, 28;
EXEC addProductToMenu 'Walnut', 3, 32;
EXEC addProductToMenu 'Chocolate', 3, 31;
EXEC addProductToMenu 'Chocolate bar', 3, 17;
EXEC addProductToMenu 'Chocolate candy', 3, 12;
EXEC addProductToMenu 'Chocolate candy bar', 3, 25;
EXEC addProductToMenu 'Chocolate candy stick', 3, 29;
EXEC addProductToMenu 'Chocolate candy roll', 3, 28;
EXEC addProductToMenu 'Chocolate candy sandwich', 3, 15;
EXEC addProductToMenu 'Chocolate candy sandwich roll', 3, 25;