EXEC addProductToOrder 100, 3, 'Cookie sandwich'
EXEC addProductToOrder 100, 3, 'Butter pecan ice cream'
EXEC addProductToOrder 100, 3, 'Coconut cake'
EXEC addProductToOrder 100, 2, 'Bleu cheese'
EXEC addProductToOrder 100, 3, 'Beef stew with mushrooms'
EXEC addProductToOrder 101, 2, 'Chocolate ice cream'
EXEC addProductToOrder 101, 1, 'Pasta with clams'
EXEC addProductToOrder 101, 3, 'Diet Mountain Dew'
EXEC addProductToOrder 101, 1, 'Anise'
EXEC addProductToOrder 101, 1, 'Pineapple juice'
EXEC addProductToOrder 102, 1, 'Caprese salad'
EXEC addProductToOrder 102, 1, 'Bundt cake'
EXEC addProductToOrder 102, 1, 'Café del mar'
EXEC addProductToOrder 102, 3, 'Cumin'
EXEC addProductToOrder 102, 2, 'Crab cakes with a remoulade sauce'
EXEC addProductToOrder 103, 1, 'Grilled octopus with a citrus marinade'
EXEC addProductToOrder 103, 1, 'Pan-seared scallops with a white wine sauce'
EXEC addProductToOrder 103, 2, 'Apple juice'
EXEC addProductToOrder 103, 1, 'Boursin cheese'
EXEC addProductToOrder 103, 3, 'Fish stick'
EXEC addProductToOrder 104, 2, 'Carrot salad'
EXEC addProductToOrder 104, 3, 'Greek salad'
EXEC addProductToOrder 104, 3, 'Apple'
EXEC addProductToOrder 104, 3, 'Chocolate peanut butter ice cream'
EXEC addProductToOrder 104, 3, 'Sprite'
EXEC addProductToOrder 105, 3, 'Corn chowder'
EXEC addProductToOrder 105, 2, 'Biscuit sandwich roll'
EXEC addProductToOrder 105, 2, 'Cashew'
EXEC addProductToOrder 105, 1, 'Cobb salad'
EXEC addProductToOrder 105, 3, 'Minestrone soup'
EXEC addProductToOrder 106, 3, 'Pasta with chicken'
EXEC addProductToOrder 106, 2, 'Romano cheese'
EXEC addProductToOrder 106, 1, 'Breadstick'
EXEC addProductToOrder 106, 3, 'Biscuit sandwich roll'
EXEC addProductToOrder 106, 2, 'Brioche'
EXEC addProductToOrder 107, 1, 'Vanilla pudding'
EXEC addProductToOrder 107, 3, 'Blueberry'
EXEC addProductToOrder 107, 1, 'Vegetable chili'
EXEC addProductToOrder 107, 3, 'Pasta with cauliflower'
EXEC addProductToOrder 107, 1, 'Tzatziki'
EXEC addProductToOrder 108, 1, 'Baked stuffed zucchini'
EXEC addProductToOrder 108, 3, 'Fried mushrooms'
EXEC addProductToOrder 108, 1, 'Rice pudding'
EXEC addProductToOrder 108, 1, 'Pasta with broccoli'
EXEC addProductToOrder 108, 1, 'Chicken and barley soup'
EXEC addProductToOrder 109, 2, 'Chili'
EXEC addProductToOrder 109, 1, 'Rocky road ice cream'
EXEC addProductToOrder 109, 2, 'Pasta with onions'
EXEC addProductToOrder 109, 1, 'Beet salad'
EXEC addProductToOrder 109, 1, '7 Up'
EXEC addProductToOrder 110, 3, 'Fish roll'
EXEC addProductToOrder 110, 3, 'Pistachio ice cream'
EXEC addProductToOrder 110, 1, 'Cashew'
EXEC addProductToOrder 110, 1, 'Beef stew with cabbage'
EXEC addProductToOrder 110, 1, 'Diet Sprite'
EXEC addProductToOrder 111, 3, 'Fried potato skins'
EXEC addProductToOrder 111, 2, 'Chicken and barley soup'
EXEC addProductToOrder 111, 1, 'Fanta'
EXEC addProductToOrder 111, 2, 'Vegetable casserole'
EXEC addProductToOrder 111, 2, 'Flat white'
EXEC addProductToOrder 112, 3, 'Bay leaf'
EXEC addProductToOrder 112, 2, 'Tomato soup'
EXEC addProductToOrder 112, 2, 'Biscuit'
EXEC addProductToOrder 112, 2, 'Strawberry ice cream'
EXEC addProductToOrder 112, 2, 'Caramel sauce'
EXEC addProductToOrder 113, 3, 'Cherry'
EXEC addProductToOrder 113, 1, 'Blueberry juice'
EXEC addProductToOrder 113, 3, 'Bun'
EXEC addProductToOrder 113, 2, 'Café mocha'
EXEC addProductToOrder 113, 2, 'Café gourmand'
EXEC addProductToOrder 114, 3, 'Macadamia'
EXEC addProductToOrder 114, 1, 'Latte'
EXEC addProductToOrder 114, 2, 'Tomato juice'
EXEC addProductToOrder 114, 2, 'Boursin cheese'
EXEC addProductToOrder 114, 3, 'Cookies and cream ice cream'
EXEC addProductToOrder 115, 3, 'Espresso'
EXEC addProductToOrder 115, 1, 'Herbal tea'
EXEC addProductToOrder 115, 1, 'Chocolate'
EXEC addProductToOrder 115, 3, 'Biscuit sandwich bun'
EXEC addProductToOrder 115, 3, 'Pasta with tomatoes'
EXEC addProductToOrder 116, 1, 'Biscuit'
EXEC addProductToOrder 116, 1, 'Fish roll'
EXEC addProductToOrder 116, 1, 'Coconut pudding'
EXEC addProductToOrder 116, 3, 'Basil'
EXEC addProductToOrder 116, 3, 'Café del mar'
EXEC addProductToOrder 117, 2, 'Tossed salad'
EXEC addProductToOrder 117, 1, 'Cereal sandwich stick'
EXEC addProductToOrder 117, 2, 'Potato soup'
EXEC addProductToOrder 117, 1, 'Vegetable casserole'
EXEC addProductToOrder 117, 2, 'Café de pico'
EXEC addProductToOrder 118, 2, 'Cereal roll'
EXEC addProductToOrder 118, 1, 'Raspberry juice'
EXEC addProductToOrder 118, 3, 'Biscuit sandwich'
EXEC addProductToOrder 118, 3, 'Strawberry pudding'
EXEC addProductToOrder 118, 3, 'Beef stew with celery'
EXEC addProductToOrder 119, 3, 'Chocolate pudding'
EXEC addProductToOrder 119, 3, 'Beef stew with carrots'
EXEC addProductToOrder 119, 2, 'Diet Sierra Mist'
EXEC addProductToOrder 119, 1, 'Spinach salad'
EXEC addProductToOrder 119, 1, 'Fish sandwich stick'
EXEC addProductToOrder 120, 2, 'Cookie sandwich bun'
EXEC addProductToOrder 120, 1, 'Baked brie'
EXEC addProductToOrder 120, 2, 'Macaroni salad'
EXEC addProductToOrder 120, 2, 'Moose tracks ice cream'
EXEC addProductToOrder 120, 3, 'Cheesecake'
EXEC addProductToOrder 121, 2, 'Chicken and mushroom soup'
EXEC addProductToOrder 121, 3, 'Espresso'
EXEC addProductToOrder 121, 1, 'Dijon sauce'
EXEC addProductToOrder 121, 2, 'Pepsi'
EXEC addProductToOrder 121, 2, 'Raspberry juice'
EXEC addProductToOrder 122, 3, 'Baked stuffed peppers'
EXEC addProductToOrder 122, 2, 'Beef stew with potatoes'
EXEC addProductToOrder 122, 2, 'Cereal sandwich'
EXEC addProductToOrder 122, 2, 'Apple custard'
EXEC addProductToOrder 122, 2, 'Biscuit roll'
EXEC addProductToOrder 123, 3, 'Walnut'
EXEC addProductToOrder 123, 3, 'White tea'
EXEC addProductToOrder 123, 3, 'Chocolate bar'
EXEC addProductToOrder 123, 1, 'Vegetable stew'
EXEC addProductToOrder 123, 2, 'Cinnamon'
EXEC addProductToOrder 124, 1, 'Chicken and rice soup'
EXEC addProductToOrder 124, 3, 'Coconut pudding'
EXEC addProductToOrder 124, 2, 'Pasta with eggplant'
EXEC addProductToOrder 124, 1, 'Americano'
EXEC addProductToOrder 124, 2, 'Apple'
EXEC addProductToOrder 125, 2, 'Baked crab dip'
EXEC addProductToOrder 125, 3, 'Biscuit sandwich'
EXEC addProductToOrder 125, 3, 'Greek salad'
EXEC addProductToOrder 125, 2, 'Cloves'
EXEC addProductToOrder 125, 3, 'Grilled salmon with a lemon butter sauce'
EXEC addProductToOrder 126, 3, 'Bun'
EXEC addProductToOrder 126, 2, 'Avocado salad'
EXEC addProductToOrder 126, 1, 'Chicken noodle soup'
EXEC addProductToOrder 126, 3, 'Beef soup'
EXEC addProductToOrder 126, 3, 'Lentil soup'
EXEC addProductToOrder 127, 2, 'Hazelnut'
EXEC addProductToOrder 127, 2, 'Basil'
EXEC addProductToOrder 127, 1, 'Baked brie'
EXEC addProductToOrder 127, 3, 'Dip'
EXEC addProductToOrder 127, 3, 'Café marrón'
EXEC addProductToOrder 128, 3, 'Coke Zero'
EXEC addProductToOrder 128, 3, 'Curry'
EXEC addProductToOrder 128, 1, 'Orange juice'
EXEC addProductToOrder 128, 3, 'Banana cake'
EXEC addProductToOrder 128, 2, 'Sprite'
EXEC addProductToOrder 129, 2, 'Tomato juice'
EXEC addProductToOrder 129, 3, 'Fried onion rings'
EXEC addProductToOrder 129, 1, 'Celery seed'
EXEC addProductToOrder 129, 2, 'Pomegranate juice'
EXEC addProductToOrder 129, 3, 'Lime juice'
EXEC addProductToOrder 130, 1, 'Beef stew with onions'
EXEC addProductToOrder 130, 2, 'Pecan'
EXEC addProductToOrder 130, 3, 'Chestnut'
EXEC addProductToOrder 130, 1, 'Split pea soup'
EXEC addProductToOrder 130, 2, 'Baked stuffed eggplant'
EXEC addProductToOrder 131, 2, 'Strawberry juice'
EXEC addProductToOrder 131, 2, 'Date'
EXEC addProductToOrder 131, 2, 'Deviled eggs'
EXEC addProductToOrder 131, 1, 'Cereal sandwich roll'
EXEC addProductToOrder 131, 1, 'Crab cakes with a remoulade sauce'
EXEC addProductToOrder 132, 2, 'Rocky road ice cream'
EXEC addProductToOrder 132, 3, 'Tzatziki'
EXEC addProductToOrder 132, 2, 'Chocolate peanut butter ice cream'
EXEC addProductToOrder 132, 2, 'Cookie sandwich bun'
EXEC addProductToOrder 132, 1, 'Apricot'
EXEC addProductToOrder 133, 3, 'Latte'
EXEC addProductToOrder 133, 3, 'Vanilla ice cream'
EXEC addProductToOrder 133, 3, 'Orange juice'
EXEC addProductToOrder 133, 1, 'Pecan'
EXEC addProductToOrder 133, 1, 'Grilled octopus with a citrus marinade'
EXEC addProductToOrder 134, 1, 'Grapefruit'
EXEC addProductToOrder 134, 3, 'Cloves'
EXEC addProductToOrder 134, 1, 'Café del mar'
EXEC addProductToOrder 134, 2, 'Beef soup'
EXEC addProductToOrder 134, 2, 'Baked oysters'
EXEC addProductToOrder 135, 2, 'Pasta with zucchini'
EXEC addProductToOrder 135, 2, 'Pasta with salmon'
EXEC addProductToOrder 135, 1, 'Lime juice'
EXEC addProductToOrder 135, 3, 'Banana pudding'
EXEC addProductToOrder 135, 1, 'Pasta with spinach'
EXEC addProductToOrder 136, 1, 'Fish roll'
EXEC addProductToOrder 136, 1, 'Chicken noodle soup'
EXEC addProductToOrder 136, 1, 'Burrata cheese'
EXEC addProductToOrder 136, 3, 'Romano cheese'
EXEC addProductToOrder 136, 3, 'Diet Sprite'
EXEC addProductToOrder 137, 3, 'Pasta with clams'
EXEC addProductToOrder 137, 3, 'Cheesecake'
EXEC addProductToOrder 137, 1, 'Chocolate cake'
EXEC addProductToOrder 137, 3, 'Cereal sandwich'
EXEC addProductToOrder 137, 1, 'Baked stuffed eggplant'
EXEC addProductToOrder 138, 2, 'Flat white'
EXEC addProductToOrder 138, 2, 'Cookie sandwich roll'
EXEC addProductToOrder 138, 2, 'Fish'
EXEC addProductToOrder 138, 2, 'Peanut'
EXEC addProductToOrder 138, 1, 'Gouda cheese'
EXEC addProductToOrder 139, 3, 'Bisque sauce'
EXEC addProductToOrder 139, 3, 'Pasta with onions'
EXEC addProductToOrder 139, 3, 'Chef salad'
EXEC addProductToOrder 139, 2, 'Chocolate peanut butter ice cream'
EXEC addProductToOrder 139, 2, 'Lime juice'
EXEC addProductToOrder 140, 3, 'Tossed salad'
EXEC addProductToOrder 140, 3, 'Date'
EXEC addProductToOrder 140, 3, 'Cloves'
EXEC addProductToOrder 140, 1, 'Cereal stick'
EXEC addProductToOrder 140, 3, 'Mate tea'
EXEC addProductToOrder 141, 1, 'Mint chocolate chip ice cream'
EXEC addProductToOrder 141, 2, 'Tzatziki'
EXEC addProductToOrder 141, 2, 'Mango'
EXEC addProductToOrder 141, 1, 'Beef stew with mushrooms'
EXEC addProductToOrder 141, 3, 'Fig'
EXEC addProductToOrder 142, 3, 'Caprese salad'
EXEC addProductToOrder 142, 3, 'Pasta with meatballs'
EXEC addProductToOrder 142, 2, 'Cinnamon'
EXEC addProductToOrder 142, 3, 'Café mélange'
EXEC addProductToOrder 142, 2, 'Banana custard'
EXEC addProductToOrder 143, 1, 'Baked stuffed eggplant'
EXEC addProductToOrder 143, 3, 'Chicken and wild rice soup'
EXEC addProductToOrder 143, 2, 'Lemon custard'
EXEC addProductToOrder 143, 3, 'Vanilla pudding'
EXEC addProductToOrder 143, 3, 'Banana cake'
EXEC addProductToOrder 144, 3, 'Fruit salad'
EXEC addProductToOrder 144, 2, 'Burrata cheese'
EXEC addProductToOrder 144, 2, 'Corn chowder'
EXEC addProductToOrder 144, 1, 'Bread'
EXEC addProductToOrder 144, 3, 'Cookie sandwich roll'
EXEC addProductToOrder 145, 3, 'Lemon pudding'
EXEC addProductToOrder 145, 3, 'Baked stuffed squash'
EXEC addProductToOrder 145, 2, 'Beef casserole'
EXEC addProductToOrder 145, 3, 'Guacamole'
EXEC addProductToOrder 145, 3, 'Cumin'
EXEC addProductToOrder 146, 2, 'Muenster cheese'
EXEC addProductToOrder 146, 2, 'Biscuit sandwich'
EXEC addProductToOrder 146, 1, 'Cereal stick'
EXEC addProductToOrder 146, 3, 'Cranberry juice'
EXEC addProductToOrder 146, 1, 'Mate tea'
EXEC addProductToOrder 147, 1, 'Guacamole'
EXEC addProductToOrder 147, 2, 'Baked stuffed potatoes'
EXEC addProductToOrder 147, 2, 'Avocado'
EXEC addProductToOrder 147, 2, 'Artichoke salad'
EXEC addProductToOrder 147, 1, 'Café bombón'
EXEC addProductToOrder 148, 3, 'Lime'
EXEC addProductToOrder 148, 2, 'Romano cheese'
EXEC addProductToOrder 148, 2, 'Pasta with crab'
EXEC addProductToOrder 148, 3, 'Chicken and rice soup'
EXEC addProductToOrder 148, 3, 'Café gourmand'
EXEC addProductToOrder 149, 3, 'Biscuit sandwich stick'
EXEC addProductToOrder 149, 1, 'Lobster tail with drawn butter'
EXEC addProductToOrder 149, 3, 'Pumpkin pudding'
EXEC addProductToOrder 149, 2, 'Diet 7 Up'
EXEC addProductToOrder 149, 1, 'Baked stuffed squash'
EXEC addProductToOrder 150, 2, 'Beef stew with potatoes'
EXEC addProductToOrder 150, 1, 'Vegetable stir fry'
EXEC addProductToOrder 150, 2, 'Diet Mountain Dew'
EXEC addProductToOrder 150, 2, 'Oolong tea'
EXEC addProductToOrder 150, 3, 'Café mélange'
EXEC addProductToOrder 151, 2, 'Coca-Cola'
EXEC addProductToOrder 151, 2, 'Yellow tea'
EXEC addProductToOrder 151, 1, 'Strawberry juice'
EXEC addProductToOrder 151, 1, 'Cookie roll'
EXEC addProductToOrder 151, 1, 'Fish sandwich'
EXEC addProductToOrder 152, 1, 'Beef stew with celery'
EXEC addProductToOrder 152, 1, 'Raspberry juice'
EXEC addProductToOrder 152, 2, 'Asparagus salad'
EXEC addProductToOrder 152, 1, 'Cereal sandwich'
EXEC addProductToOrder 152, 2, 'Cobb salad'
EXEC addProductToOrder 153, 2, 'Chocolate chip ice cream'
EXEC addProductToOrder 153, 2, 'Beef stew with celery'
EXEC addProductToOrder 153, 3, 'Crab cakes with a remoulade sauce'
EXEC addProductToOrder 153, 2, 'Dijon sauce'
EXEC addProductToOrder 153, 1, 'Café marrón'
EXEC addProductToOrder 154, 1, 'Mocha'
EXEC addProductToOrder 154, 1, 'Calamari fritti (deep-fried squid)'
EXEC addProductToOrder 154, 3, 'Beef stew with dumplings'
EXEC addProductToOrder 154, 1, 'Pomegranate juice'
EXEC addProductToOrder 154, 1, 'Biscuit sandwich'
EXEC addProductToOrder 155, 1, 'Coconut pudding'
EXEC addProductToOrder 155, 3, 'Crab cakes with a remoulade sauce'
EXEC addProductToOrder 155, 1, 'Dip'
EXEC addProductToOrder 155, 1, 'Brown sauce'
EXEC addProductToOrder 155, 1, 'Bechamel sauce'
EXEC addProductToOrder 156, 3, 'Basil'
EXEC addProductToOrder 156, 1, 'Vegetable soup'
EXEC addProductToOrder 156, 1, 'Cherry'
EXEC addProductToOrder 156, 3, 'Cheddar cheese'
EXEC addProductToOrder 156, 2, 'Black tea'
EXEC addProductToOrder 157, 2, 'Chocolate pudding'
EXEC addProductToOrder 157, 1, 'Chocolate cake'
EXEC addProductToOrder 157, 1, 'Bleu cheese'
EXEC addProductToOrder 157, 2, 'Butter roll'
EXEC addProductToOrder 157, 2, 'Romano cheese'
EXEC addProductToOrder 158, 2, 'Pasta with chicken'
EXEC addProductToOrder 158, 1, 'Coriander'
EXEC addProductToOrder 158, 2, 'Brie cheese'
EXEC addProductToOrder 158, 2, 'Pistachio'
EXEC addProductToOrder 158, 1, 'Pasta with mushrooms'
EXEC addProductToOrder 159, 1, 'Vanilla ice cream'
EXEC addProductToOrder 159, 2, 'Romano cheese'
EXEC addProductToOrder 159, 3, 'Boursin cheese'
EXEC addProductToOrder 159, 3, 'Blueberry'
EXEC addProductToOrder 159, 1, 'Apple custard'
EXEC addProductToOrder 160, 1, 'Romano cheese'
EXEC addProductToOrder 160, 2, 'Fish stick'
EXEC addProductToOrder 160, 1, 'Orange juice'
EXEC addProductToOrder 160, 1, 'Peach custard'
EXEC addProductToOrder 160, 1, 'Crab cakes with a remoulade sauce'
EXEC addProductToOrder 161, 3, 'Baked stuffed potatoes'
EXEC addProductToOrder 161, 2, 'Raspberry juice'
EXEC addProductToOrder 161, 3, 'Strawberry ice cream'
EXEC addProductToOrder 161, 3, 'Pasta with meatballs'
EXEC addProductToOrder 161, 1, 'Cookie stick'
EXEC addProductToOrder 162, 3, 'Coke Zero'
EXEC addProductToOrder 162, 1, 'Chocolate cake'
EXEC addProductToOrder 162, 2, 'Diet Sierra Mist'
EXEC addProductToOrder 162, 3, 'Vanilla pudding'
EXEC addProductToOrder 162, 1, 'Apple pudding'
EXEC addProductToOrder 163, 2, 'Baked stuffed tomatoes'
EXEC addProductToOrder 163, 1, 'Avocado'
EXEC addProductToOrder 163, 3, 'Pasta with spinach'
EXEC addProductToOrder 163, 1, 'Biscuit sandwich stick'
EXEC addProductToOrder 163, 3, 'Chocolate'
EXEC addProductToOrder 164, 2, 'Cocktail sauce'
EXEC addProductToOrder 164, 3, 'Chocolate bar'
EXEC addProductToOrder 164, 2, 'Beet salad'
EXEC addProductToOrder 164, 3, 'Baked stuffed squash'
EXEC addProductToOrder 164, 1, 'Garden salad'
EXEC addProductToOrder 165, 2, 'Crab cakes with a remoulade sauce'
EXEC addProductToOrder 165, 2, 'Biscuit sandwich bun'
EXEC addProductToOrder 165, 2, 'Lemon'
EXEC addProductToOrder 165, 2, 'Chocolate candy sandwich'
EXEC addProductToOrder 165, 1, 'Fried okra'
EXEC addProductToOrder 166, 2, 'Chef salad'
EXEC addProductToOrder 166, 3, 'Cortado'
EXEC addProductToOrder 166, 1, 'Beef stew with carrots'
EXEC addProductToOrder 166, 3, 'Cookie stick'
EXEC addProductToOrder 166, 3, 'Coconut pudding'
EXEC addProductToOrder 167, 2, 'Strawberry juice'
EXEC addProductToOrder 167, 3, 'Chocolate bar'
EXEC addProductToOrder 167, 3, 'Chicken and broccoli soup'
EXEC addProductToOrder 167, 3, 'Cloves'
EXEC addProductToOrder 167, 1, 'Butter'
EXEC addProductToOrder 168, 2, 'Curry'
EXEC addProductToOrder 168, 1, 'Banana pudding'
EXEC addProductToOrder 168, 2, 'Baked stuffed tomatoes'
EXEC addProductToOrder 168, 2, 'Pasta with shrimp'
EXEC addProductToOrder 168, 2, 'Alfredo sauce'
EXEC addProductToOrder 169, 3, 'Crab cakes with a remoulade sauce'
EXEC addProductToOrder 169, 2, 'Corn salad'
EXEC addProductToOrder 169, 1, 'Coconut'
EXEC addProductToOrder 169, 2, 'Black tea'
EXEC addProductToOrder 169, 1, 'Pasta with shrimp'
EXEC addProductToOrder 170, 2, 'Muenster cheese'
EXEC addProductToOrder 170, 2, 'Chicken and wild rice soup'
EXEC addProductToOrder 170, 2, 'Fried okra'
EXEC addProductToOrder 170, 2, 'Affogato'
EXEC addProductToOrder 170, 3, 'Diet Pepsi'
EXEC addProductToOrder 171, 2, 'Cranberry juice'
EXEC addProductToOrder 171, 3, 'Biscuit roll'
EXEC addProductToOrder 171, 3, 'Vanilla pudding'
EXEC addProductToOrder 171, 2, 'Split pea soup'
EXEC addProductToOrder 171, 1, 'Pepsi'
EXEC addProductToOrder 172, 2, 'Fried mushrooms'
EXEC addProductToOrder 172, 2, 'Biscuit sandwich'
EXEC addProductToOrder 172, 2, 'Alfredo sauce'
EXEC addProductToOrder 172, 1, 'Cocktail sauce'
EXEC addProductToOrder 172, 3, '7 Up'
EXEC addProductToOrder 173, 1, 'Caramel sauce'
EXEC addProductToOrder 173, 2, 'Chocolate peanut butter ice cream'
EXEC addProductToOrder 173, 3, 'Macadamia'
EXEC addProductToOrder 173, 1, 'Fried onion rings'
EXEC addProductToOrder 173, 3, 'Fried calamari'
EXEC addProductToOrder 174, 1, 'Pasta with onions'
EXEC addProductToOrder 174, 2, 'Pasta with crab'
EXEC addProductToOrder 174, 3, 'Americano'
EXEC addProductToOrder 174, 3, 'Chocolate candy sandwich roll'
EXEC addProductToOrder 174, 3, 'Chicken and broccoli soup'
EXEC addProductToOrder 175, 2, 'Chocolate ice cream'
EXEC addProductToOrder 175, 2, 'Fried green tomatoes'
EXEC addProductToOrder 175, 3, 'Swiss cheese'
EXEC addProductToOrder 175, 2, 'Caramel sauce'
EXEC addProductToOrder 175, 1, 'Biscuit roll'
EXEC addProductToOrder 176, 2, 'Chocolate bar'
EXEC addProductToOrder 176, 1, 'Vegetable lasagna'
EXEC addProductToOrder 176, 1, 'Pasta with scallops'
EXEC addProductToOrder 176, 3, 'Baked stuffed potatoes'
EXEC addProductToOrder 176, 3, 'Baked stuffed squash'
EXEC addProductToOrder 177, 1, 'Pasta with tomatoes'
EXEC addProductToOrder 177, 1, 'Coconut'
EXEC addProductToOrder 177, 3, 'Chai tea'
EXEC addProductToOrder 177, 1, 'Goat cheese'
EXEC addProductToOrder 177, 3, 'Biscotti'
EXEC addProductToOrder 178, 3, 'Greek salad'
EXEC addProductToOrder 178, 3, 'Pasta with meatballs'
EXEC addProductToOrder 178, 3, 'Pasta with eggplant'
EXEC addProductToOrder 178, 1, 'Chicken tortilla soup'
EXEC addProductToOrder 178, 2, 'Butter'
EXEC addProductToOrder 179, 1, 'Muenster cheese'
EXEC addProductToOrder 179, 2, 'Potato salad'
EXEC addProductToOrder 179, 3, 'Cortado'
EXEC addProductToOrder 179, 3, 'Latte'
EXEC addProductToOrder 179, 1, 'Potato soup'
EXEC addProductToOrder 180, 2, 'Beef stew with dumplings'
EXEC addProductToOrder 180, 2, 'Allspice'
EXEC addProductToOrder 180, 3, 'Beef casserole'
EXEC addProductToOrder 180, 2, 'Burrata cheese'
EXEC addProductToOrder 180, 2, 'Bread'
EXEC addProductToOrder 181, 2, 'Butter pecan ice cream'
EXEC addProductToOrder 181, 1, 'Cereal sandwich stick'
EXEC addProductToOrder 181, 1, 'Pasta with salmon'
EXEC addProductToOrder 181, 2, 'Bleu cheese'
EXEC addProductToOrder 181, 2, 'Potato soup'
EXEC addProductToOrder 182, 1, 'Pasta with tuna'
EXEC addProductToOrder 182, 3, 'Chicken and barley soup'
EXEC addProductToOrder 182, 2, 'Honeybush tea'
EXEC addProductToOrder 182, 2, 'Fanta'
EXEC addProductToOrder 182, 2, 'Banana cake'
EXEC addProductToOrder 183, 3, 'Chutney sauce'
EXEC addProductToOrder 183, 1, 'Chicken and broccoli soup'
EXEC addProductToOrder 183, 2, 'Beef stew with potatoes'
EXEC addProductToOrder 183, 2, 'Chestnut'
EXEC addProductToOrder 183, 1, 'Biscuit roll'
EXEC addProductToOrder 184, 1, 'Yellow tea'
EXEC addProductToOrder 184, 3, 'Lemon juice'
EXEC addProductToOrder 184, 3, 'Kombucha tea'
EXEC addProductToOrder 184, 3, 'Carrot cake'
EXEC addProductToOrder 184, 3, 'Hummus'
EXEC addProductToOrder 185, 1, 'Guacamole'
EXEC addProductToOrder 185, 2, 'Celery seed'
EXEC addProductToOrder 185, 1, 'Chocolate chip ice cream'
EXEC addProductToOrder 185, 2, 'Coconut cake'
EXEC addProductToOrder 185, 2, 'Chocolate candy'
EXEC addProductToOrder 186, 2, 'Pasta with crab'
EXEC addProductToOrder 186, 2, 'Baked crab dip'
EXEC addProductToOrder 186, 3, 'Cardamom'
EXEC addProductToOrder 186, 3, 'Café gourmand'
EXEC addProductToOrder 186, 1, 'Baked stuffed artichokes'
EXEC addProductToOrder 187, 3, 'Cereal'
EXEC addProductToOrder 187, 3, 'Fish sandwich roll'
EXEC addProductToOrder 187, 3, 'Black tea'
EXEC addProductToOrder 187, 2, 'Beef stew with tomatoes'
EXEC addProductToOrder 187, 2, 'Pistachio ice cream'
EXEC addProductToOrder 188, 3, 'Black forest cake'
EXEC addProductToOrder 188, 2, 'Coconut'
EXEC addProductToOrder 188, 3, 'Pasta with crab'
EXEC addProductToOrder 188, 1, 'Green tea'
EXEC addProductToOrder 188, 3, 'Vegetable soup'
EXEC addProductToOrder 189, 3, 'Café con leche'
EXEC addProductToOrder 189, 2, 'Coconut'
EXEC addProductToOrder 189, 1, 'Caprese salad'
EXEC addProductToOrder 189, 1, 'Café de olla'
EXEC addProductToOrder 189, 3, 'Vegetable casserole'
EXEC addProductToOrder 190, 1, 'Baked oysters'
EXEC addProductToOrder 190, 1, 'Chicken and broccoli soup'
EXEC addProductToOrder 190, 2, 'Banana custard'
EXEC addProductToOrder 190, 3, 'Affogato'
EXEC addProductToOrder 190, 2, 'Cereal sandwich stick'
EXEC addProductToOrder 191, 1, '7 Up'
EXEC addProductToOrder 191, 3, 'Orange'
EXEC addProductToOrder 191, 1, 'Biscuit sandwich'
EXEC addProductToOrder 191, 3, 'Split pea soup'
EXEC addProductToOrder 191, 2, 'Café Cubano'
EXEC addProductToOrder 192, 1, 'Kombucha tea'
EXEC addProductToOrder 192, 1, 'Banana'
EXEC addProductToOrder 192, 3, 'Cucumber salad'
EXEC addProductToOrder 192, 2, 'Beef casserole'
EXEC addProductToOrder 192, 3, 'Diet Sierra Mist'
EXEC addProductToOrder 193, 3, 'Baked stuffed artichokes'
EXEC addProductToOrder 193, 2, 'Americano'
EXEC addProductToOrder 193, 1, 'Cole slaw'
EXEC addProductToOrder 193, 1, 'Dip'
EXEC addProductToOrder 193, 3, 'Muenster cheese'
EXEC addProductToOrder 194, 2, 'Chicken and corn chowder'
EXEC addProductToOrder 194, 3, 'Pasta with salmon'
EXEC addProductToOrder 194, 1, 'Apple juice'
EXEC addProductToOrder 194, 3, 'Fried mozzarella sticks'
EXEC addProductToOrder 194, 2, 'Pepsi'
EXEC addProductToOrder 195, 1, 'Pistachio'
EXEC addProductToOrder 195, 3, 'Apple'
EXEC addProductToOrder 195, 3, 'Pasta with onions'
EXEC addProductToOrder 195, 1, 'Shrimp scampi served over pasta'
EXEC addProductToOrder 195, 3, 'Gruyere cheese'
EXEC addProductToOrder 196, 1, 'Pasta with salmon'
EXEC addProductToOrder 196, 3, 'Broccoli salad'
EXEC addProductToOrder 196, 1, 'Café de pico'
EXEC addProductToOrder 196, 3, 'Spinach salad'
EXEC addProductToOrder 196, 1, 'Kombucha tea'
EXEC addProductToOrder 197, 1, 'Brown sauce'
EXEC addProductToOrder 197, 3, 'Matcha tea'
EXEC addProductToOrder 197, 3, 'Pepper jack cheese'
EXEC addProductToOrder 197, 2, 'Grapefruit juice'
EXEC addProductToOrder 197, 3, 'Mountain Dew'
EXEC addProductToOrder 198, 1, 'Bread'
EXEC addProductToOrder 198, 3, 'Cayenne'
EXEC addProductToOrder 198, 1, 'Baked stuffed tomatoes'
EXEC addProductToOrder 198, 2, 'Cranberry'
EXEC addProductToOrder 198, 2, 'Gruyere cheese'
EXEC addProductToOrder 199, 1, 'Banana cake'
EXEC addProductToOrder 199, 1, 'Caraway'
EXEC addProductToOrder 199, 2, 'Mint chocolate chip ice cream'
EXEC addProductToOrder 199, 3, 'Chocolate cake'
EXEC addProductToOrder 199, 1, 'Chicken casserole'
EXEC addProductToOrder 200, 3, 'Salsa'
EXEC addProductToOrder 200, 3, 'Fish sandwich bun'
EXEC addProductToOrder 200, 1, 'Hummus'
EXEC addProductToOrder 200, 2, 'Rooibos tea'
EXEC addProductToOrder 200, 1, 'Calamari fritti (deep-fried squid)'
EXEC addProductToOrder 201, 3, 'Cookie sandwich bun'
EXEC addProductToOrder 201, 2, 'Café bombón'
EXEC addProductToOrder 201, 3, 'Chocolate candy'
EXEC addProductToOrder 201, 3, 'Vegetable soup'
EXEC addProductToOrder 201, 2, 'Vegetable stew'
EXEC addProductToOrder 202, 1, 'Café mélange'
EXEC addProductToOrder 202, 1, 'Gouda cheese'
EXEC addProductToOrder 202, 2, 'Cherry'
EXEC addProductToOrder 202, 1, 'Café mocha'
EXEC addProductToOrder 202, 3, 'Fried mozzarella sticks'
EXEC addProductToOrder 203, 3, 'Pasta with crab'
EXEC addProductToOrder 203, 3, 'Espresso'
EXEC addProductToOrder 203, 2, 'Chicken and dumplings'
EXEC addProductToOrder 203, 2, 'Strawberry juice'
EXEC addProductToOrder 203, 1, 'Rooibos tea'
EXEC addProductToOrder 204, 1, 'Alfredo sauce'
EXEC addProductToOrder 204, 2, 'Fish sandwich'
EXEC addProductToOrder 204, 2, 'Mint chocolate chip ice cream'
EXEC addProductToOrder 204, 3, 'Bundt cake'
EXEC addProductToOrder 204, 1, 'Fried okra'
EXEC addProductToOrder 205, 1, 'Banana cake'
EXEC addProductToOrder 205, 3, 'Chestnut'
EXEC addProductToOrder 205, 2, 'Brie cheese'
EXEC addProductToOrder 205, 1, 'Romano cheese'
EXEC addProductToOrder 205, 2, 'Pasta with tuna'
EXEC addProductToOrder 206, 1, 'Apricot'
EXEC addProductToOrder 206, 3, 'Parmesan cheese'
EXEC addProductToOrder 206, 2, 'Blueberry'
EXEC addProductToOrder 206, 2, 'Cocktail sauce'
EXEC addProductToOrder 206, 2, 'Cereal sandwich'
EXEC addProductToOrder 207, 2, 'Crab cakes with a remoulade sauce'
EXEC addProductToOrder 207, 3, 'Cobb salad'
EXEC addProductToOrder 207, 1, 'Curry'
EXEC addProductToOrder 207, 1, 'Café crema'
EXEC addProductToOrder 207, 2, 'Cranberry juice'
EXEC addProductToOrder 208, 2, 'Fish sandwich stick'
EXEC addProductToOrder 208, 2, 'Lentil soup'
EXEC addProductToOrder 208, 2, 'Dijon sauce'
EXEC addProductToOrder 208, 2, 'Vegetable stir fry'
EXEC addProductToOrder 208, 3, 'Romano cheese'
EXEC addProductToOrder 209, 1, 'Pasta with tuna'
EXEC addProductToOrder 209, 2, 'Fish sandwich stick'
EXEC addProductToOrder 209, 1, 'Pasta with clams'
EXEC addProductToOrder 209, 3, 'Pasta with mussels'
EXEC addProductToOrder 209, 2, 'Chicken soup'
EXEC addProductToOrder 210, 2, 'Lemon juice'
EXEC addProductToOrder 210, 3, 'Anise'
EXEC addProductToOrder 210, 2, 'Beef stew with celery'
EXEC addProductToOrder 210, 3, 'Sprite'
EXEC addProductToOrder 210, 2, 'Cortado'
EXEC addProductToOrder 211, 3, 'Lemon'
EXEC addProductToOrder 211, 1, 'Cereal sandwich stick'
EXEC addProductToOrder 211, 1, 'Curry sauce'
EXEC addProductToOrder 211, 2, 'Café mélange'
EXEC addProductToOrder 211, 2, 'White tea'
EXEC addProductToOrder 212, 1, 'Americano'
EXEC addProductToOrder 212, 1, 'Biscuit sandwich roll'
EXEC addProductToOrder 212, 2, 'Bechamel sauce'
EXEC addProductToOrder 212, 2, 'Fish sandwich bun'
EXEC addProductToOrder 212, 3, 'Corn chowder'
EXEC addProductToOrder 213, 1, 'Celery seed'
EXEC addProductToOrder 213, 2, 'Fried zucchini'
EXEC addProductToOrder 213, 2, 'Mozzarella cheese'
EXEC addProductToOrder 213, 2, 'Broccoli salad'
EXEC addProductToOrder 213, 1, 'Caprese salad'
EXEC addProductToOrder 214, 1, 'Vanilla ice cream'
EXEC addProductToOrder 214, 1, 'Beef stew with potatoes'
EXEC addProductToOrder 214, 2, 'Peach custard'
EXEC addProductToOrder 214, 2, 'Gruyere cheese'
EXEC addProductToOrder 214, 2, 'Cucumber salad'
EXEC addProductToOrder 215, 1, 'Chimichurri sauce'
EXEC addProductToOrder 215, 1, 'Americano'
EXEC addProductToOrder 215, 2, 'Peach custard'
EXEC addProductToOrder 215, 3, 'Shrimp scampi served over pasta'
EXEC addProductToOrder 215, 1, 'Chai tea'
EXEC addProductToOrder 216, 2, 'Cappuccino'
EXEC addProductToOrder 216, 2, 'Dressing sauce'
EXEC addProductToOrder 216, 3, 'Diet 7 Up'
EXEC addProductToOrder 216, 3, 'Black tea'
EXEC addProductToOrder 216, 1, 'Tomato salad'
EXEC addProductToOrder 217, 3, 'Chocolate'
EXEC addProductToOrder 217, 2, 'Curry'
EXEC addProductToOrder 217, 2, 'Apple juice'
EXEC addProductToOrder 217, 3, 'Caper sauce'
EXEC addProductToOrder 217, 1, 'Sierra Mist'
EXEC addProductToOrder 218, 1, 'Coke Zero'
EXEC addProductToOrder 218, 3, 'Dip'
EXEC addProductToOrder 218, 2, 'Cranberry'
EXEC addProductToOrder 218, 3, 'Pomegranate juice'
EXEC addProductToOrder 218, 2, 'Baked crab dip'
EXEC addProductToOrder 219, 2, 'Lemon juice'
EXEC addProductToOrder 219, 1, 'Pasta with spinach'
EXEC addProductToOrder 219, 2, 'Swiss cheese'
EXEC addProductToOrder 219, 3, 'Lime juice'
EXEC addProductToOrder 219, 1, 'Avocado salad'
EXEC addProductToOrder 220, 3, 'Fish sandwich roll'
EXEC addProductToOrder 220, 2, 'Chocolate chip ice cream'
EXEC addProductToOrder 220, 1, 'Chocolate cake'
EXEC addProductToOrder 220, 3, 'Parmesan cheese'
EXEC addProductToOrder 220, 2, 'Lemon'
EXEC addProductToOrder 221, 2, 'Cookies and cream ice cream'
EXEC addProductToOrder 221, 1, 'Cherry'
EXEC addProductToOrder 221, 1, 'Chicken and corn chowder'
EXEC addProductToOrder 221, 2, 'Pasta with broccoli'
EXEC addProductToOrder 221, 2, 'Fish stick'
EXEC addProductToOrder 222, 1, 'Bleu cheese'
EXEC addProductToOrder 222, 1, 'Macaroni salad'
EXEC addProductToOrder 222, 2, 'Chocolate custard'
EXEC addProductToOrder 222, 3, 'Alfredo sauce'
EXEC addProductToOrder 222, 1, 'Biscuit'
EXEC addProductToOrder 223, 3, 'Boston cream cake'
EXEC addProductToOrder 223, 1, 'Strawberry juice'
EXEC addProductToOrder 223, 2, 'Grape juice'
EXEC addProductToOrder 223, 1, 'Mango'
EXEC addProductToOrder 223, 3, 'Anise'
EXEC addProductToOrder 224, 2, 'Baked stuffed shrimp'
EXEC addProductToOrder 224, 1, 'Swiss cheese'
EXEC addProductToOrder 224, 3, 'Kombucha tea'
EXEC addProductToOrder 224, 2, 'Butter'
EXEC addProductToOrder 224, 3, 'Diet Pepsi'
EXEC addProductToOrder 225, 1, 'Angel food cake'
EXEC addProductToOrder 225, 1, 'Caper sauce'
EXEC addProductToOrder 225, 3, 'Chicken and rice soup'
EXEC addProductToOrder 225, 1, 'Basil'
EXEC addProductToOrder 225, 2, 'Fried calamari'
EXEC addProductToOrder 226, 2, 'Macchiato'
EXEC addProductToOrder 226, 2, 'Fried mushrooms'
EXEC addProductToOrder 226, 3, 'Tuna tartare with avocado and soy sauce'
EXEC addProductToOrder 226, 1, 'Swiss cheese'
EXEC addProductToOrder 226, 2, 'Fried mozzarella sticks'
EXEC addProductToOrder 227, 1, 'Café crema'
EXEC addProductToOrder 227, 1, 'Swiss cheese'
EXEC addProductToOrder 227, 3, 'Peach pudding'
EXEC addProductToOrder 227, 2, 'Basil'
EXEC addProductToOrder 227, 3, 'Chicken and corn chowder'
EXEC addProductToOrder 228, 3, 'Café con leche'
EXEC addProductToOrder 228, 1, 'Vegetable stew'
EXEC addProductToOrder 228, 2, 'Baked stuffed artichokes'
EXEC addProductToOrder 228, 3, 'Café gourmand'
EXEC addProductToOrder 228, 2, 'Chili'
EXEC addProductToOrder 229, 3, 'Cortado'
EXEC addProductToOrder 229, 1, 'Chicken tortilla soup'
EXEC addProductToOrder 229, 1, 'Chocolate pudding'
EXEC addProductToOrder 229, 1, 'Baked stuffed shrimp'
EXEC addProductToOrder 229, 3, 'Curry'
EXEC addProductToOrder 230, 2, 'Basil'
EXEC addProductToOrder 230, 3, 'Pasta with chicken'
EXEC addProductToOrder 230, 2, 'Split pea soup'
EXEC addProductToOrder 230, 1, 'Chimichurri sauce'
EXEC addProductToOrder 230, 2, 'Baked stuffed shrimp'
EXEC addProductToOrder 231, 2, 'Cookie sandwich'
EXEC addProductToOrder 231, 3, 'Baked stuffed shrimp'
EXEC addProductToOrder 231, 3, 'Carrot cake'
EXEC addProductToOrder 231, 1, 'Strawberry pudding'
EXEC addProductToOrder 231, 1, 'Chocolate pudding'
EXEC addProductToOrder 232, 2, 'Baked crab dip'
EXEC addProductToOrder 232, 1, 'Cranberry juice'
EXEC addProductToOrder 232, 1, 'Beef soup'
EXEC addProductToOrder 232, 2, 'Asparagus salad'
EXEC addProductToOrder 232, 2, 'Fish sandwich stick'
EXEC addProductToOrder 233, 2, 'Vegetable casserole'
EXEC addProductToOrder 233, 3, 'Chocolate cake'
EXEC addProductToOrder 233, 1, 'Mate tea'
EXEC addProductToOrder 233, 2, 'Chicken and wild rice soup'
EXEC addProductToOrder 233, 2, 'Baked stuffed tomatoes'
EXEC addProductToOrder 234, 2, 'Fish sandwich roll'
EXEC addProductToOrder 234, 3, 'Diet 7 Up'
EXEC addProductToOrder 234, 1, 'Romano cheese'
EXEC addProductToOrder 234, 2, 'Pasta with onions'
EXEC addProductToOrder 234, 2, 'Broccoli salad'
EXEC addProductToOrder 235, 1, 'Bleu cheese'
EXEC addProductToOrder 235, 3, 'Pasta with shrimp'
EXEC addProductToOrder 235, 3, 'Boursin cheese'
EXEC addProductToOrder 235, 1, 'Baked clams'
EXEC addProductToOrder 235, 1, 'American cheese'
EXEC addProductToOrder 236, 1, 'Pasta with salmon'
EXEC addProductToOrder 236, 1, 'Chocolate peanut butter ice cream'
EXEC addProductToOrder 236, 1, 'Fruit salad'
EXEC addProductToOrder 236, 1, 'Chocolate candy bar'
EXEC addProductToOrder 236, 3, 'Café au lait'
EXEC addProductToOrder 237, 1, 'Chicken noodle soup'
EXEC addProductToOrder 237, 3, 'Cranberry'
EXEC addProductToOrder 237, 2, 'Vegetable soup'
EXEC addProductToOrder 237, 3, 'Biscuit'
EXEC addProductToOrder 237, 2, 'Coca-Cola'
EXEC addProductToOrder 238, 3, 'Fried green tomatoes'
EXEC addProductToOrder 238, 2, 'Fried mozzarella sticks'
EXEC addProductToOrder 238, 3, 'Chicken and mushroom soup'
EXEC addProductToOrder 238, 2, 'Fried pickles'
EXEC addProductToOrder 238, 1, 'Chocolate bar'
EXEC addProductToOrder 239, 3, 'Chicken noodle soup'
EXEC addProductToOrder 239, 1, 'Fish stick'
EXEC addProductToOrder 239, 2, 'White tea'
EXEC addProductToOrder 239, 2, 'Vanilla pudding'
EXEC addProductToOrder 239, 3, 'Brioche'
EXEC addProductToOrder 240, 1, 'Chocolate candy roll'
EXEC addProductToOrder 240, 2, 'French onion soup'
EXEC addProductToOrder 240, 2, 'Cookie'
EXEC addProductToOrder 240, 3, 'Mango'
EXEC addProductToOrder 240, 1, 'Pasta with onions'
EXEC addProductToOrder 241, 2, 'Tossed salad'
EXEC addProductToOrder 241, 2, 'Biscuit roll'
EXEC addProductToOrder 241, 2, 'Grilled salmon with a lemon butter sauce'
EXEC addProductToOrder 241, 3, 'Coconut'
EXEC addProductToOrder 241, 3, 'Banana cake'
EXEC addProductToOrder 242, 1, 'Greek salad'
EXEC addProductToOrder 242, 2, 'Macadamia'
EXEC addProductToOrder 242, 1, 'Apple juice'
EXEC addProductToOrder 242, 3, 'Black tea'
EXEC addProductToOrder 242, 2, 'Rice pudding'
EXEC addProductToOrder 243, 2, 'Chicken noodle soup'
EXEC addProductToOrder 243, 3, 'Café marrón'
EXEC addProductToOrder 243, 3, 'Beef stew with dumplings'
EXEC addProductToOrder 243, 3, 'Split pea soup'
EXEC addProductToOrder 243, 2, 'Pumpkin pudding'
EXEC addProductToOrder 244, 1, 'Caper sauce'
EXEC addProductToOrder 244, 2, 'Black tea'
EXEC addProductToOrder 244, 1, 'Banana cake'
EXEC addProductToOrder 244, 3, 'Cucumber salad'
EXEC addProductToOrder 244, 1, 'Yellow tea'
EXEC addProductToOrder 245, 3, 'American cheese'
EXEC addProductToOrder 245, 2, 'Cole slaw'
EXEC addProductToOrder 245, 1, 'Chocolate candy stick'
EXEC addProductToOrder 245, 3, 'Chestnut'
EXEC addProductToOrder 245, 1, 'Chocolate candy'
EXEC addProductToOrder 246, 1, 'Vegetable soup'
EXEC addProductToOrder 246, 3, 'Pasta with mushrooms'
EXEC addProductToOrder 246, 1, 'Caesar salad'
EXEC addProductToOrder 246, 3, 'Hummus'
EXEC addProductToOrder 246, 1, 'Hazelnut'
EXEC addProductToOrder 247, 3, 'Fish sandwich roll'
EXEC addProductToOrder 247, 3, 'Cloves'
EXEC addProductToOrder 247, 3, 'Cardamom'
EXEC addProductToOrder 247, 1, 'Macadamia'
EXEC addProductToOrder 247, 2, 'Pasta with mussels'
EXEC addProductToOrder 248, 2, 'Provolone cheese'
EXEC addProductToOrder 248, 2, 'Alfredo sauce'
EXEC addProductToOrder 248, 2, 'Café marrón'
EXEC addProductToOrder 248, 2, 'Breadstick'
EXEC addProductToOrder 248, 2, 'Apple juice'
EXEC addProductToOrder 249, 3, 'Curry'
EXEC addProductToOrder 249, 3, 'Vegetable curry'
EXEC addProductToOrder 249, 3, 'Carrot juice'
EXEC addProductToOrder 249, 1, 'Date'
EXEC addProductToOrder 249, 2, 'Grilled salmon with a lemon butter sauce'
EXEC addProductToOrder 250, 2, 'Salsa'
EXEC addProductToOrder 250, 2, 'Diet Coke'
EXEC addProductToOrder 250, 1, 'Diet Sprite'
EXEC addProductToOrder 250, 3, 'Cereal sandwich stick'
EXEC addProductToOrder 250, 1, 'Kombucha tea'
EXEC addProductToOrder 251, 1, 'Fig'
EXEC addProductToOrder 251, 3, 'Black tea'
EXEC addProductToOrder 251, 3, 'Chef salad'
EXEC addProductToOrder 251, 3, 'Shrimp scampi served over pasta'
EXEC addProductToOrder 251, 3, 'Tomato juice'
EXEC addProductToOrder 252, 2, 'Grape juice'
EXEC addProductToOrder 252, 3, 'Cookie sandwich'
EXEC addProductToOrder 252, 2, 'Cranberry juice'
EXEC addProductToOrder 252, 2, 'Pasta with crab'
EXEC addProductToOrder 252, 3, 'Beef stew with mushrooms'
EXEC addProductToOrder 253, 2, 'Grape'
EXEC addProductToOrder 253, 2, 'Beef casserole'
EXEC addProductToOrder 253, 2, 'Beef soup'
EXEC addProductToOrder 253, 2, 'Chocolate ice cream'
EXEC addProductToOrder 253, 2, 'Coconut'
EXEC addProductToOrder 254, 3, 'Café au lait'
EXEC addProductToOrder 254, 1, 'Strawberry pudding'
EXEC addProductToOrder 254, 2, 'Baked stuffed mushrooms'
EXEC addProductToOrder 254, 3, 'Bundt cake'
EXEC addProductToOrder 254, 1, 'Garden salad'
EXEC addProductToOrder 255, 2, 'Beef stew with carrots'
EXEC addProductToOrder 255, 2, 'Fried calamari'
EXEC addProductToOrder 255, 3, 'Cucumber salad'
EXEC addProductToOrder 255, 3, 'Tomato soup'
EXEC addProductToOrder 255, 2, 'Banana pudding'
EXEC addProductToOrder 256, 3, 'Chef salad'
EXEC addProductToOrder 256, 2, 'Fish roll'
EXEC addProductToOrder 256, 3, 'Swiss cheese'
EXEC addProductToOrder 256, 1, 'Pumpkin pudding'
EXEC addProductToOrder 256, 2, 'Antipasto salad'
EXEC addProductToOrder 257, 3, 'Banana'
EXEC addProductToOrder 257, 3, 'Rice pudding'
EXEC addProductToOrder 257, 2, 'Vanilla pudding'
EXEC addProductToOrder 257, 3, 'Pepsi'
EXEC addProductToOrder 257, 3, 'Café del mar'
EXEC addProductToOrder 258, 1, 'Pasta with cauliflower'
EXEC addProductToOrder 258, 2, 'Pecan'
EXEC addProductToOrder 258, 1, 'Apricot'
EXEC addProductToOrder 258, 3, 'Brown sauce'
EXEC addProductToOrder 258, 1, 'Tomato juice'
EXEC addProductToOrder 259, 3, 'Chutney sauce'
EXEC addProductToOrder 259, 2, 'Tomato salad'
EXEC addProductToOrder 259, 3, 'Cookie sandwich'
EXEC addProductToOrder 259, 1, 'Orange juice'
EXEC addProductToOrder 259, 2, 'Chocolate candy roll'
EXEC addProductToOrder 260, 2, 'Café con leche'
EXEC addProductToOrder 260, 1, 'Corn salad'
EXEC addProductToOrder 260, 1, 'Pasta with crab'
EXEC addProductToOrder 260, 3, 'Baked stuffed peppers'
EXEC addProductToOrder 260, 1, 'Alfredo sauce'
EXEC addProductToOrder 261, 2, 'Chicken tortilla soup'
EXEC addProductToOrder 261, 2, 'Fried onion rings'
EXEC addProductToOrder 261, 1, 'Brown sauce'
EXEC addProductToOrder 261, 3, 'Dijon sauce'
EXEC addProductToOrder 261, 1, 'Lemon custard'
EXEC addProductToOrder 262, 3, 'Dr Pepper'
EXEC addProductToOrder 262, 2, 'Baked crab dip'
EXEC addProductToOrder 262, 2, 'Allspice'
EXEC addProductToOrder 262, 3, 'Vegetable lasagna'
EXEC addProductToOrder 262, 1, 'Fried calamari'
EXEC addProductToOrder 263, 1, 'Caraway'
EXEC addProductToOrder 263, 3, 'Lemon juice'
EXEC addProductToOrder 263, 3, 'Fish sandwich'
EXEC addProductToOrder 263, 2, 'Pu-erh tea'
EXEC addProductToOrder 263, 1, 'Chocolate chip cookie dough ice cream'
EXEC addProductToOrder 264, 1, 'Café gourmand'
EXEC addProductToOrder 264, 2, 'Diet Dr Pepper'
EXEC addProductToOrder 264, 3, 'Pasta with broccoli'
EXEC addProductToOrder 264, 1, 'Goat cheese'
EXEC addProductToOrder 264, 2, 'Grilled salmon with a lemon butter sauce'
EXEC addProductToOrder 265, 1, 'Caesar salad'
EXEC addProductToOrder 265, 1, 'Cardamom'
EXEC addProductToOrder 265, 3, 'Café marrón'
EXEC addProductToOrder 265, 3, 'Banana cake'
EXEC addProductToOrder 265, 3, 'Lemon pudding'
EXEC addProductToOrder 266, 1, 'Latte'
EXEC addProductToOrder 266, 3, 'Strawberry ice cream'
EXEC addProductToOrder 266, 3, 'Lemon custard'
EXEC addProductToOrder 266, 3, 'Lentil soup'
EXEC addProductToOrder 266, 3, 'Sprite'
EXEC addProductToOrder 267, 2, 'Café Cubano'
EXEC addProductToOrder 267, 2, 'Almond'
EXEC addProductToOrder 267, 2, 'Chicken and barley soup'
EXEC addProductToOrder 267, 3, 'Mint chocolate chip ice cream'
EXEC addProductToOrder 267, 3, 'Fish roll'
EXEC addProductToOrder 268, 2, 'Beef stew with carrots'
EXEC addProductToOrder 268, 3, 'Oolong tea'
EXEC addProductToOrder 268, 2, 'White tea'
EXEC addProductToOrder 268, 3, 'Avocado'
EXEC addProductToOrder 268, 1, 'Grapefruit'
EXEC addProductToOrder 269, 1, 'Biscuit roll'
EXEC addProductToOrder 269, 1, 'Honeybush tea'
EXEC addProductToOrder 269, 2, 'Coconut cake'
EXEC addProductToOrder 269, 3, 'Apricot'
EXEC addProductToOrder 269, 3, 'Chocolate custard'
EXEC addProductToOrder 270, 3, 'Orange'
EXEC addProductToOrder 270, 3, 'Chocolate ice cream'
EXEC addProductToOrder 270, 2, 'Diet Pepsi'
EXEC addProductToOrder 270, 3, 'Vanilla ice cream'
EXEC addProductToOrder 270, 2, 'Café zorro'
EXEC addProductToOrder 271, 3, 'Fried onion rings'
EXEC addProductToOrder 271, 3, 'Peanut'
EXEC addProductToOrder 271, 2, 'Butter pecan ice cream'
EXEC addProductToOrder 271, 3, 'Mate tea'
EXEC addProductToOrder 271, 3, 'Vegetable soup'
EXEC addProductToOrder 272, 2, 'Chicken and barley soup'
EXEC addProductToOrder 272, 1, 'Vegetable lasagna'
EXEC addProductToOrder 272, 2, 'Baked brie'
EXEC addProductToOrder 272, 1, 'Pasta with scallops'
EXEC addProductToOrder 272, 3, 'Caprese salad'
EXEC addProductToOrder 273, 3, 'Fried okra'
EXEC addProductToOrder 273, 1, 'Coconut pudding'
EXEC addProductToOrder 273, 2, 'Beef stew with mushrooms'
EXEC addProductToOrder 273, 2, 'Asiago cheese'
EXEC addProductToOrder 273, 3, 'Bechamel sauce'
EXEC addProductToOrder 274, 2, 'Corn chowder'
EXEC addProductToOrder 274, 2, 'Coconut custard'
EXEC addProductToOrder 274, 2, 'Chestnut'
EXEC addProductToOrder 274, 3, 'Chocolate candy bar'
EXEC addProductToOrder 274, 1, 'Split pea soup'
EXEC addProductToOrder 275, 2, 'Celery seed'
EXEC addProductToOrder 275, 1, 'Cherry'
EXEC addProductToOrder 275, 3, 'Fried onion rings'
EXEC addProductToOrder 275, 1, 'Burrata cheese'
EXEC addProductToOrder 275, 3, 'Apple custard'
EXEC addProductToOrder 276, 3, 'Vegetable soup'
EXEC addProductToOrder 276, 2, 'Kiwi'
EXEC addProductToOrder 276, 2, 'Cereal stick'
EXEC addProductToOrder 276, 3, 'Cappuccino'
EXEC addProductToOrder 276, 3, 'Burrata cheese'
EXEC addProductToOrder 277, 1, 'Cinnamon'
EXEC addProductToOrder 277, 2, 'Herbal tea'
EXEC addProductToOrder 277, 2, 'Split pea soup'
EXEC addProductToOrder 277, 2, 'Macchiato'
EXEC addProductToOrder 277, 2, 'Pan-seared scallops with a white wine sauce'
EXEC addProductToOrder 278, 2, 'Baked brie'
EXEC addProductToOrder 278, 2, 'Lemon custard'
EXEC addProductToOrder 278, 2, 'Gouda cheese'
EXEC addProductToOrder 278, 1, 'Chocolate candy stick'
EXEC addProductToOrder 278, 2, 'Apricot'
EXEC addProductToOrder 279, 1, 'Lemon pudding'
EXEC addProductToOrder 279, 2, 'Bread'
EXEC addProductToOrder 279, 2, 'Baked crab dip'
EXEC addProductToOrder 279, 1, 'Blueberry juice'
EXEC addProductToOrder 279, 2, 'Celery seed'
EXEC addProductToOrder 280, 3, 'Bun'
EXEC addProductToOrder 280, 2, 'Café au lait'
EXEC addProductToOrder 280, 1, 'Pasta with salmon'
EXEC addProductToOrder 280, 1, 'Pasta with scallops'
EXEC addProductToOrder 280, 3, 'Baked stuffed clams'
EXEC addProductToOrder 281, 1, 'Lemon custard'
EXEC addProductToOrder 281, 2, 'Vegetable chili'
EXEC addProductToOrder 281, 3, 'Blackberry'
EXEC addProductToOrder 281, 1, 'Hazelnut'
EXEC addProductToOrder 281, 3, 'Mango'
EXEC addProductToOrder 282, 1, 'Beef stew with onions'
EXEC addProductToOrder 282, 3, 'Baked stuffed squash'
EXEC addProductToOrder 282, 3, 'Cheesecake'
EXEC addProductToOrder 282, 1, 'Pistachio ice cream'
EXEC addProductToOrder 282, 2, 'Avocado'
EXEC addProductToOrder 283, 2, 'Cocktail sauce'
EXEC addProductToOrder 283, 2, 'Tuna tartare with avocado and soy sauce'
EXEC addProductToOrder 283, 1, 'Fish stick'
EXEC addProductToOrder 283, 3, 'Baked stuffed shrimp'
EXEC addProductToOrder 283, 2, 'Bundt cake'
EXEC addProductToOrder 284, 3, 'Chef salad'
EXEC addProductToOrder 284, 2, 'Date'
EXEC addProductToOrder 284, 2, 'Grapefruit'
EXEC addProductToOrder 284, 3, 'Coffee cake'
EXEC addProductToOrder 284, 2, 'Banana pudding'
EXEC addProductToOrder 285, 1, 'Gruyere cheese'
EXEC addProductToOrder 285, 3, 'Bay leaf'
EXEC addProductToOrder 285, 3, 'Chocolate bar'
EXEC addProductToOrder 285, 2, 'Cookie roll'
EXEC addProductToOrder 285, 3, 'Hummus'
EXEC addProductToOrder 286, 3, 'Mate tea'
EXEC addProductToOrder 286, 2, 'Macadamia'
EXEC addProductToOrder 286, 3, 'Cranberry juice'
EXEC addProductToOrder 286, 2, 'Swiss cheese'
EXEC addProductToOrder 286, 2, 'Peach pudding'
EXEC addProductToOrder 287, 1, 'Muenster cheese'
EXEC addProductToOrder 287, 1, 'Café con leche'
EXEC addProductToOrder 287, 3, 'Bleu cheese'
EXEC addProductToOrder 287, 2, 'Fig'
EXEC addProductToOrder 287, 2, 'Cortado'
EXEC addProductToOrder 288, 1, 'Chicken and broccoli soup'
EXEC addProductToOrder 288, 1, 'Lime juice'
EXEC addProductToOrder 288, 3, 'Brown sauce'
EXEC addProductToOrder 288, 2, 'Cranberry juice'
EXEC addProductToOrder 288, 1, 'Dressing sauce'
EXEC addProductToOrder 289, 2, '7 Up'
EXEC addProductToOrder 289, 3, 'Macaroni salad'
EXEC addProductToOrder 289, 3, 'Fried zucchini'
EXEC addProductToOrder 289, 2, 'Fried green tomatoes'
EXEC addProductToOrder 289, 1, 'Chicken and dumplings'
EXEC addProductToOrder 290, 3, 'Minestrone soup'
EXEC addProductToOrder 290, 1, 'Chicken tortilla soup'
EXEC addProductToOrder 290, 1, 'Beef stew with potatoes'
EXEC addProductToOrder 290, 3, 'Cheesecake'
EXEC addProductToOrder 290, 3, 'Coffee cake'
EXEC addProductToOrder 291, 3, 'Tomato salad'
EXEC addProductToOrder 291, 1, 'Corn chowder'
EXEC addProductToOrder 291, 2, 'Vanilla ice cream'
EXEC addProductToOrder 291, 3, 'Pistachio'
EXEC addProductToOrder 291, 2, 'Chocolate custard'
EXEC addProductToOrder 292, 3, 'Honeybush tea'
EXEC addProductToOrder 292, 1, 'Pasta with mussels'
EXEC addProductToOrder 292, 3, 'Pasta with tomatoes'
EXEC addProductToOrder 292, 2, 'Dijon sauce'
EXEC addProductToOrder 292, 1, '7 Up'
EXEC addProductToOrder 293, 1, 'Baked stuffed mushrooms'
EXEC addProductToOrder 293, 1, 'Beet salad'
EXEC addProductToOrder 293, 2, 'Beef soup'
EXEC addProductToOrder 293, 2, 'Baked stuffed peppers'
EXEC addProductToOrder 293, 2, 'Cole slaw'
EXEC addProductToOrder 294, 2, 'Chicken and rice soup'
EXEC addProductToOrder 294, 3, 'Cloves'
EXEC addProductToOrder 294, 2, 'Fried ravioli'
EXEC addProductToOrder 294, 3, 'Chocolate pudding'
EXEC addProductToOrder 294, 1, 'Feta cheese'
EXEC addProductToOrder 295, 2, 'Espresso'
EXEC addProductToOrder 295, 1, 'Cucumber salad'
EXEC addProductToOrder 295, 2, 'Lemon juice'
EXEC addProductToOrder 295, 2, 'Muenster cheese'
EXEC addProductToOrder 295, 1, 'Affogato'
EXEC addProductToOrder 296, 3, 'Pasta with salmon'
EXEC addProductToOrder 296, 1, 'Chocolate candy sandwich'
EXEC addProductToOrder 296, 3, 'Asiago cheese'
EXEC addProductToOrder 296, 3, 'Vegetable chili'
EXEC addProductToOrder 296, 1, 'Pasta with tuna'
EXEC addProductToOrder 297, 1, 'Alfredo sauce'
EXEC addProductToOrder 297, 3, 'Fried potato skins'
EXEC addProductToOrder 297, 1, 'Romano cheese'
EXEC addProductToOrder 297, 3, 'Pasta with salmon'
EXEC addProductToOrder 297, 1, 'Café irlandés'
EXEC addProductToOrder 298, 1, 'Beef stew with onions'
EXEC addProductToOrder 298, 1, 'Chocolate candy sandwich'
EXEC addProductToOrder 298, 1, 'Fish'
EXEC addProductToOrder 298, 1, 'Garden salad'
EXEC addProductToOrder 298, 2, 'Cookie sandwich stick'
EXEC addProductToOrder 299, 1, 'Rooibos tea'
EXEC addProductToOrder 299, 3, 'Grape juice'
EXEC addProductToOrder 299, 1, 'Cocktail sauce'
EXEC addProductToOrder 299, 2, 'Macchiato'
EXEC addProductToOrder 299, 2, 'Vegetable soup'
EXEC addProductToOrder 300, 2, 'Butter pecan ice cream'
EXEC addProductToOrder 300, 3, 'Chocolate chip ice cream'
EXEC addProductToOrder 300, 3, 'Melon'
EXEC addProductToOrder 300, 1, 'Rooibos tea'
EXEC addProductToOrder 300, 3, 'Affogato'
EXEC addProductToOrder 1, 3, 'Strawberry juice'
EXEC addProductToOrder 1, 1, 'Vanilla pudding'
EXEC addProductToOrder 1, 2, 'Chocolate'
EXEC addProductToOrder 1, 3, 'Apple juice'
EXEC addProductToOrder 1, 3, 'Apricot'
EXEC addProductToOrder 2, 2, 'Oolong tea'
EXEC addProductToOrder 2, 1, 'Rocky road ice cream'
EXEC addProductToOrder 2, 2, 'Date'
EXEC addProductToOrder 2, 2, 'Latte'
EXEC addProductToOrder 2, 1, 'Café irlandés'
EXEC addProductToOrder 3, 2, 'Cookie sandwich'
EXEC addProductToOrder 3, 1, 'Chocolate custard'
EXEC addProductToOrder 3, 2, 'Dressing sauce'
EXEC addProductToOrder 3, 3, 'Pasta with shrimp'
EXEC addProductToOrder 3, 2, 'Cookie sandwich stick'
EXEC addProductToOrder 4, 1, 'Baked stuffed peppers'
EXEC addProductToOrder 4, 1, 'Coke Zero'
EXEC addProductToOrder 4, 2, 'Beef stew with mushrooms'
EXEC addProductToOrder 4, 1, 'Black tea'
EXEC addProductToOrder 4, 3, 'Chicken casserole'
EXEC addProductToOrder 5, 3, 'Fried potato skins'
EXEC addProductToOrder 5, 1, 'Corn chowder'
EXEC addProductToOrder 5, 2, 'Cumin'
EXEC addProductToOrder 5, 2, 'Apple pudding'
EXEC addProductToOrder 5, 3, 'Boston cream cake'
EXEC addProductToOrder 6, 1, 'Tuna tartare with avocado and soy sauce'
EXEC addProductToOrder 6, 2, 'Baguette'
EXEC addProductToOrder 6, 3, 'Chicken and mushroom soup'
EXEC addProductToOrder 6, 2, 'Chicken casserole'
EXEC addProductToOrder 6, 3, 'Café gourmand'
EXEC addProductToOrder 7, 3, 'Diet Mountain Dew'
EXEC addProductToOrder 7, 3, 'Peanut'
EXEC addProductToOrder 7, 1, 'Pasta with shrimp'
EXEC addProductToOrder 7, 3, 'American cheese'
EXEC addProductToOrder 7, 1, 'Blueberry'
EXEC addProductToOrder 8, 2, 'Hazelnut'
EXEC addProductToOrder 8, 2, 'Lobster tail with drawn butter'
EXEC addProductToOrder 8, 2, 'Mountain Dew'
EXEC addProductToOrder 8, 3, 'Potato salad'
EXEC addProductToOrder 8, 3, 'Beef stew with cabbage'
EXEC addProductToOrder 9, 1, 'Rocky road ice cream'
EXEC addProductToOrder 9, 1, 'Café del mar'
EXEC addProductToOrder 9, 1, 'Burrata cheese'
EXEC addProductToOrder 9, 3, 'Café irlandés'
EXEC addProductToOrder 9, 3, 'Cereal roll'
EXEC addProductToOrder 10, 2, 'Pistachio'
EXEC addProductToOrder 10, 3, 'Boursin cheese'
EXEC addProductToOrder 10, 1, 'Brioche'
EXEC addProductToOrder 10, 1, 'Chicken and wild rice soup'
EXEC addProductToOrder 10, 2, 'Coconut custard'
EXEC addProductToOrder 11, 1, 'Blueberry juice'
EXEC addProductToOrder 11, 2, 'Fried onion rings'
EXEC addProductToOrder 11, 3, 'Cereal roll'
EXEC addProductToOrder 11, 3, 'Butter pecan ice cream'
EXEC addProductToOrder 11, 2, 'Fried mozzarella sticks'
EXEC addProductToOrder 12, 1, 'Fruit salad'
EXEC addProductToOrder 12, 2, 'Biscuit sandwich bun'
EXEC addProductToOrder 12, 1, 'Parmesan cheese'
EXEC addProductToOrder 12, 2, 'Cranberry'
EXEC addProductToOrder 12, 3, 'Cheesecake'
EXEC addProductToOrder 13, 3, 'Chocolate chip cookie dough ice cream'
EXEC addProductToOrder 13, 1, 'Moose tracks ice cream'
EXEC addProductToOrder 13, 3, 'Broccoli salad'
EXEC addProductToOrder 13, 3, 'Chili'
EXEC addProductToOrder 13, 2, 'Chocolate candy sandwich'
EXEC addProductToOrder 14, 1, 'Cereal roll'
EXEC addProductToOrder 14, 1, 'Chocolate chip ice cream'
EXEC addProductToOrder 14, 3, 'Mate tea'
EXEC addProductToOrder 14, 2, 'Gouda cheese'
EXEC addProductToOrder 14, 1, 'Pasta with spinach'
EXEC addProductToOrder 15, 3, 'Caesar salad'
EXEC addProductToOrder 15, 2, 'Fried mozzarella sticks'
EXEC addProductToOrder 15, 1, 'Blueberry'
EXEC addProductToOrder 15, 1, 'Pasta with broccoli'
EXEC addProductToOrder 15, 2, 'Baked oysters'
EXEC addProductToOrder 16, 3, 'Lobster tail with drawn butter'
EXEC addProductToOrder 16, 3, 'Fruit salad'
EXEC addProductToOrder 16, 3, 'Chili'
EXEC addProductToOrder 16, 2, 'Bechamel sauce'
EXEC addProductToOrder 16, 1, 'Baked stuffed tomatoes'
EXEC addProductToOrder 17, 3, 'Boursin cheese'
EXEC addProductToOrder 17, 2, 'Café irlandés'
EXEC addProductToOrder 17, 3, 'Beef stew with celery'
EXEC addProductToOrder 17, 1, 'Diet Sprite'
EXEC addProductToOrder 17, 2, 'Carrot salad'
EXEC addProductToOrder 18, 2, 'Lime'
EXEC addProductToOrder 18, 1, 'Angel food cake'
EXEC addProductToOrder 18, 2, 'Coconut pudding'
EXEC addProductToOrder 18, 3, 'Black forest cake'
EXEC addProductToOrder 18, 3, 'Baked stuffed shrimp'
EXEC addProductToOrder 19, 3, 'Cereal sandwich roll'
EXEC addProductToOrder 19, 1, 'Macadamia'
EXEC addProductToOrder 19, 1, 'Brioche'
EXEC addProductToOrder 19, 3, 'Cranberry juice'
EXEC addProductToOrder 19, 3, 'Café gourmand'
EXEC addProductToOrder 20, 2, 'Crab cakes with a remoulade sauce'
EXEC addProductToOrder 20, 2, 'Potato soup'
EXEC addProductToOrder 20, 3, 'Fish sandwich stick'
EXEC addProductToOrder 20, 2, 'Vanilla pudding'
EXEC addProductToOrder 20, 3, 'Beef stew with potatoes'
EXEC addProductToOrder 21, 1, 'Caramel sauce'
EXEC addProductToOrder 21, 1, 'Tomato soup'
EXEC addProductToOrder 21, 2, 'Corn chowder'
EXEC addProductToOrder 21, 3, 'Angel food cake'
EXEC addProductToOrder 21, 2, 'Fish'
EXEC addProductToOrder 22, 1, 'Tzatziki'
EXEC addProductToOrder 22, 2, 'Macchiato'
EXEC addProductToOrder 22, 2, 'Banana cake'
EXEC addProductToOrder 22, 3, 'Chicken and barley soup'
EXEC addProductToOrder 22, 2, 'Cereal stick'
EXEC addProductToOrder 23, 2, 'Pistachio ice cream'
EXEC addProductToOrder 23, 3, 'Black tea'
EXEC addProductToOrder 23, 1, 'Diet Sprite'
EXEC addProductToOrder 23, 2, 'Diet Sierra Mist'
EXEC addProductToOrder 23, 3, 'Cloves'
EXEC addProductToOrder 24, 2, 'Café gourmand'
EXEC addProductToOrder 24, 2, 'Diet Fanta'
EXEC addProductToOrder 24, 3, 'Tossed salad'
EXEC addProductToOrder 24, 1, 'Cereal roll'
EXEC addProductToOrder 24, 1, 'Lime juice'
EXEC addProductToOrder 25, 2, 'Parmesan cheese'
EXEC addProductToOrder 25, 3, 'Baked stuffed zucchini'
EXEC addProductToOrder 25, 2, 'Chocolate ice cream'
EXEC addProductToOrder 25, 3, 'Grilled salmon with a lemon butter sauce'
EXEC addProductToOrder 25, 1, 'Cobb salad'
EXEC addProductToOrder 26, 1, 'Beef stew with celery'
EXEC addProductToOrder 26, 2, 'Boston cream cake'
EXEC addProductToOrder 26, 1, 'Minestrone soup'
EXEC addProductToOrder 26, 1, 'Bleu cheese'
EXEC addProductToOrder 26, 1, 'Macchiato'
EXEC addProductToOrder 27, 2, 'Cheddar cheese'
EXEC addProductToOrder 27, 2, 'Cortado'
EXEC addProductToOrder 27, 3, 'Pasta with chicken'
EXEC addProductToOrder 27, 3, 'Mozzarella cheese'
EXEC addProductToOrder 27, 1, 'Chocolate peanut butter ice cream'
EXEC addProductToOrder 28, 1, 'Butter roll'
EXEC addProductToOrder 28, 3, 'Baked oysters'
EXEC addProductToOrder 28, 2, 'Chicken and dumplings'
EXEC addProductToOrder 28, 1, 'Cereal sandwich stick'
EXEC addProductToOrder 28, 3, 'Lemon pudding'
EXEC addProductToOrder 29, 3, 'Cashew'
EXEC addProductToOrder 29, 3, 'Hazelnut'
EXEC addProductToOrder 29, 2, 'Cherry'
EXEC addProductToOrder 29, 2, 'Vegetable chili'
EXEC addProductToOrder 29, 2, 'Green tea'
EXEC addProductToOrder 30, 2, 'Rooibos tea'
EXEC addProductToOrder 30, 3, 'Vegetable curry'
EXEC addProductToOrder 30, 1, 'Cookie roll'
EXEC addProductToOrder 30, 3, 'Cookies and cream ice cream'
EXEC addProductToOrder 30, 3, 'Cereal sandwich stick'
EXEC addProductToOrder 31, 1, 'Strawberry ice cream'
EXEC addProductToOrder 31, 3, 'Dip'
EXEC addProductToOrder 31, 1, 'Butter pecan ice cream'
EXEC addProductToOrder 31, 2, 'Banana cake'
EXEC addProductToOrder 31, 2, 'Beef stew with tomatoes'
EXEC addProductToOrder 32, 3, 'Pistachio ice cream'
EXEC addProductToOrder 32, 2, 'Beef stew with cabbage'
EXEC addProductToOrder 32, 3, 'Pasta with cauliflower'
EXEC addProductToOrder 32, 3, 'Biscuit'
EXEC addProductToOrder 32, 1, 'Antipasto salad'
EXEC addProductToOrder 33, 2, 'Brie cheese'
EXEC addProductToOrder 33, 3, 'Fanta'
EXEC addProductToOrder 33, 2, 'Vegetable curry'
EXEC addProductToOrder 33, 2, 'Cereal sandwich stick'
EXEC addProductToOrder 33, 3, 'Beef stew with mushrooms'
EXEC addProductToOrder 34, 1, 'Diet Fanta'
EXEC addProductToOrder 34, 2, 'Cookie sandwich'
EXEC addProductToOrder 34, 1, 'Beef soup'
EXEC addProductToOrder 34, 3, 'Sierra Mist'
EXEC addProductToOrder 34, 3, 'Bay leaf'
EXEC addProductToOrder 35, 3, 'Cereal sandwich stick'
EXEC addProductToOrder 35, 3, 'Cookie roll'
EXEC addProductToOrder 35, 2, 'Apple pudding'
EXEC addProductToOrder 35, 1, 'Café zorro'
EXEC addProductToOrder 35, 2, 'Banana'
EXEC addProductToOrder 36, 2, 'Biscotti'
EXEC addProductToOrder 36, 1, 'Chicken and corn chowder'
EXEC addProductToOrder 36, 3, 'Corn salad'
EXEC addProductToOrder 36, 3, 'Pineapple juice'
EXEC addProductToOrder 36, 2, 'Black tea'
EXEC addProductToOrder 37, 1, 'Chocolate bar'
EXEC addProductToOrder 37, 1, 'Banana'
EXEC addProductToOrder 37, 2, 'Dip'
EXEC addProductToOrder 37, 2, '7 Up'
EXEC addProductToOrder 37, 3, 'Potato soup'
EXEC addProductToOrder 38, 2, 'Boston cream cake'
EXEC addProductToOrder 38, 2, 'Melon'
EXEC addProductToOrder 38, 3, 'Minestrone soup'
EXEC addProductToOrder 38, 3, 'Fried potato skins'
EXEC addProductToOrder 38, 1, 'Deviled eggs'
EXEC addProductToOrder 39, 3, 'Matcha tea'
EXEC addProductToOrder 39, 1, 'Curry'
EXEC addProductToOrder 39, 3, 'Chocolate candy bar'
EXEC addProductToOrder 39, 1, 'Cereal roll'
EXEC addProductToOrder 39, 2, 'Fried green tomatoes'
EXEC addProductToOrder 40, 3, 'Baked stuffed zucchini'
EXEC addProductToOrder 40, 2, 'Strawberry pudding'
EXEC addProductToOrder 40, 3, 'Pineapple juice'
EXEC addProductToOrder 40, 1, 'Bleu cheese'
EXEC addProductToOrder 40, 2, 'Pasta with zucchini'
EXEC addProductToOrder 41, 1, 'Vegetable casserole'
EXEC addProductToOrder 41, 1, 'Cookies and cream ice cream'
EXEC addProductToOrder 41, 2, 'Apple custard'
EXEC addProductToOrder 41, 3, 'Chicken soup'
EXEC addProductToOrder 41, 3, 'Cookie roll'
EXEC addProductToOrder 42, 2, 'Lobster tail with drawn butter'
EXEC addProductToOrder 42, 2, 'Mango'
EXEC addProductToOrder 42, 2, 'Kombucha tea'
EXEC addProductToOrder 42, 2, 'Vegetable lasagna'
EXEC addProductToOrder 42, 2, 'Lime juice'
EXEC addProductToOrder 43, 1, 'Café irlandés'
EXEC addProductToOrder 43, 1, 'Blackberry'
EXEC addProductToOrder 43, 3, 'Pu-erh tea'
EXEC addProductToOrder 43, 1, 'Diet Dr Pepper'
EXEC addProductToOrder 43, 1, 'Chicken and corn chowder'
EXEC addProductToOrder 44, 3, 'Café au lait'
EXEC addProductToOrder 44, 2, 'Chocolate'
EXEC addProductToOrder 44, 2, 'Greek salad'
EXEC addProductToOrder 44, 3, 'Diet Mountain Dew'
EXEC addProductToOrder 44, 2, 'Chimichurri sauce'
EXEC addProductToOrder 45, 3, 'Deviled eggs'
EXEC addProductToOrder 45, 2, 'Peanut'
EXEC addProductToOrder 45, 1, 'Tossed salad'
EXEC addProductToOrder 45, 1, 'Cheddar cheese'
EXEC addProductToOrder 45, 1, 'Fish stick'
EXEC addProductToOrder 46, 3, 'Peach pudding'
EXEC addProductToOrder 46, 1, 'Café de pico'
EXEC addProductToOrder 46, 1, 'Vanilla ice cream'
EXEC addProductToOrder 46, 1, 'Pasta with broccoli'
EXEC addProductToOrder 46, 2, 'Bleu cheese'
EXEC addProductToOrder 47, 1, 'Salsa'
EXEC addProductToOrder 47, 2, 'Broccoli salad'
EXEC addProductToOrder 47, 3, 'Beef stew with tomatoes'
EXEC addProductToOrder 47, 1, 'Clam chowder'
EXEC addProductToOrder 47, 1, 'Minestrone soup'
EXEC addProductToOrder 48, 2, 'Vegetable stew'
EXEC addProductToOrder 48, 1, 'Pasta with mushrooms'
EXEC addProductToOrder 48, 2, 'Fish'
EXEC addProductToOrder 48, 2, 'Café con leche'
EXEC addProductToOrder 48, 2, 'Orange juice'
EXEC addProductToOrder 49, 1, 'Pineapple juice'
EXEC addProductToOrder 49, 1, 'Pasta with lobster'
EXEC addProductToOrder 49, 1, 'Peanut'
EXEC addProductToOrder 49, 2, 'Beef stew with potatoes'
EXEC addProductToOrder 49, 1, 'Fish roll'
EXEC addProductToOrder 50, 3, 'Brie cheese'
EXEC addProductToOrder 50, 2, 'Cinnamon'
EXEC addProductToOrder 50, 3, 'Alfredo sauce'
EXEC addProductToOrder 50, 2, 'Pasta with zucchini'
EXEC addProductToOrder 50, 1, 'Pepper jack cheese'
EXEC addProductToOrder 51, 3, 'Strawberry ice cream'
EXEC addProductToOrder 51, 2, 'Pomegranate juice'
EXEC addProductToOrder 51, 3, 'Cookie stick'
EXEC addProductToOrder 51, 1, 'Beef soup'
EXEC addProductToOrder 51, 2, 'Chocolate candy sandwich roll'
EXEC addProductToOrder 52, 2, 'Beef stew with mushrooms'
EXEC addProductToOrder 52, 3, 'Vegetable curry'
EXEC addProductToOrder 52, 1, 'Cookies and cream ice cream'
EXEC addProductToOrder 52, 1, 'Angel food cake'
EXEC addProductToOrder 52, 1, 'Rooibos tea'
EXEC addProductToOrder 53, 1, 'Brown sauce'
EXEC addProductToOrder 53, 2, 'Vegetable casserole'
EXEC addProductToOrder 53, 2, 'Chocolate custard'
EXEC addProductToOrder 53, 2, 'Melon'
EXEC addProductToOrder 53, 1, 'Caesar salad'
EXEC addProductToOrder 54, 2, 'Chestnut'
EXEC addProductToOrder 54, 1, 'Lemon juice'
EXEC addProductToOrder 54, 1, 'Crab cakes with a remoulade sauce'
EXEC addProductToOrder 54, 1, 'Pasta with chicken'
EXEC addProductToOrder 54, 1, 'Pepper jack cheese'
EXEC addProductToOrder 55, 3, 'Fried zucchini'
EXEC addProductToOrder 55, 2, 'Rocky road ice cream'
EXEC addProductToOrder 55, 1, 'Café au lait'
EXEC addProductToOrder 55, 2, 'Cortado'
EXEC addProductToOrder 55, 3, 'Bleu cheese'
EXEC addProductToOrder 56, 3, 'Rooibos tea'
EXEC addProductToOrder 56, 3, 'Alfredo sauce'
EXEC addProductToOrder 56, 3, 'Pumpkin pudding'
EXEC addProductToOrder 56, 2, 'Brioche'
EXEC addProductToOrder 56, 3, 'Chai tea'
EXEC addProductToOrder 57, 1, 'Vegetable soup'
EXEC addProductToOrder 57, 3, 'Muenster cheese'
EXEC addProductToOrder 57, 1, 'Fish stick'
EXEC addProductToOrder 57, 3, 'Bisque sauce'
EXEC addProductToOrder 57, 1, 'Fig'
EXEC addProductToOrder 58, 3, 'Fried green tomatoes'
EXEC addProductToOrder 58, 3, 'Béarnaise sauce'
EXEC addProductToOrder 58, 2, 'Bechamel sauce'
EXEC addProductToOrder 58, 2, 'Mango'
EXEC addProductToOrder 58, 1, 'Muenster cheese'
EXEC addProductToOrder 59, 1, 'Banana custard'
EXEC addProductToOrder 59, 1, 'Cherry'
EXEC addProductToOrder 59, 3, 'Tzatziki'
EXEC addProductToOrder 59, 1, 'Rice pudding'
EXEC addProductToOrder 59, 2, 'Chocolate custard'
EXEC addProductToOrder 60, 2, 'Cookie sandwich bun'
EXEC addProductToOrder 60, 3, 'Orange juice'
EXEC addProductToOrder 60, 2, 'Yellow tea'
EXEC addProductToOrder 60, 2, 'Chocolate candy roll'
EXEC addProductToOrder 60, 2, 'Beef stew with onions'
EXEC addProductToOrder 61, 3, 'Latte'
EXEC addProductToOrder 61, 3, 'Sprite'
EXEC addProductToOrder 61, 2, 'Macaroni salad'
EXEC addProductToOrder 61, 1, 'Tzatziki'
EXEC addProductToOrder 61, 2, 'Mocha'
EXEC addProductToOrder 62, 1, 'Chicken soup'
EXEC addProductToOrder 62, 1, 'Vegetable stew'
EXEC addProductToOrder 62, 3, 'Cookie stick'
EXEC addProductToOrder 62, 3, 'Pasta with spinach'
EXEC addProductToOrder 62, 2, 'Brie cheese'
EXEC addProductToOrder 63, 2, 'Asparagus salad'
EXEC addProductToOrder 63, 2, 'Raspberry juice'
EXEC addProductToOrder 63, 2, 'Carrot juice'
EXEC addProductToOrder 63, 2, 'Vegetable soup'
EXEC addProductToOrder 63, 1, 'Pepper jack cheese'
EXEC addProductToOrder 64, 2, 'Gruyere cheese'
EXEC addProductToOrder 64, 2, 'Diet 7 Up'
EXEC addProductToOrder 64, 3, 'Boursin cheese'
EXEC addProductToOrder 64, 2, 'Cortado'
EXEC addProductToOrder 64, 3, 'Vegetable lasagna'
EXEC addProductToOrder 65, 3, 'Fanta'
EXEC addProductToOrder 65, 3, 'Orange juice'
EXEC addProductToOrder 65, 2, 'Cereal'
EXEC addProductToOrder 65, 2, 'Café mélange'
EXEC addProductToOrder 65, 2, 'Cookies and cream ice cream'
EXEC addProductToOrder 66, 2, 'Banana'
EXEC addProductToOrder 66, 2, 'Pasta with scallops'
EXEC addProductToOrder 66, 3, 'Goat cheese'
EXEC addProductToOrder 66, 2, 'Blueberry'
EXEC addProductToOrder 66, 1, 'Bechamel sauce'
EXEC addProductToOrder 67, 3, 'Cookie sandwich roll'
EXEC addProductToOrder 67, 3, 'Cereal sandwich roll'
EXEC addProductToOrder 67, 3, 'Vanilla ice cream'
EXEC addProductToOrder 67, 3, 'Baked stuffed zucchini'
EXEC addProductToOrder 67, 2, 'Biscuit sandwich bun'
EXEC addProductToOrder 68, 1, 'Asiago cheese'
EXEC addProductToOrder 68, 1, 'Baked crab dip'
EXEC addProductToOrder 68, 3, 'Baked clams'
EXEC addProductToOrder 68, 1, 'Caraway'
EXEC addProductToOrder 68, 3, 'Calamari fritti (deep-fried squid)'
EXEC addProductToOrder 69, 3, 'Cookie sandwich bun'
EXEC addProductToOrder 69, 2, 'Mango'
EXEC addProductToOrder 69, 1, 'Lime'
EXEC addProductToOrder 69, 1, 'Chutney sauce'
EXEC addProductToOrder 69, 2, 'Pistachio'
EXEC addProductToOrder 70, 1, 'Strawberry ice cream'
EXEC addProductToOrder 70, 1, 'Chili'
EXEC addProductToOrder 70, 2, 'Apple'
EXEC addProductToOrder 70, 1, 'Cookie sandwich stick'
EXEC addProductToOrder 70, 3, 'Baguette'
EXEC addProductToOrder 71, 3, 'Cocktail sauce'
EXEC addProductToOrder 71, 1, 'Chocolate candy sandwich'
EXEC addProductToOrder 71, 2, 'Cranberry'
EXEC addProductToOrder 71, 2, 'Baked crab dip'
EXEC addProductToOrder 71, 1, 'Pomegranate juice'
EXEC addProductToOrder 72, 2, 'Pasta with sausage'
EXEC addProductToOrder 72, 1, 'Apricot'
EXEC addProductToOrder 72, 3, 'Lemon'
EXEC addProductToOrder 72, 3, 'Chicken and broccoli soup'
EXEC addProductToOrder 72, 2, 'Kombucha tea'
EXEC addProductToOrder 73, 1, 'French onion soup'
EXEC addProductToOrder 73, 2, 'Banana pudding'
EXEC addProductToOrder 73, 2, 'Beef casserole'
EXEC addProductToOrder 73, 1, 'Butter roll'
EXEC addProductToOrder 73, 1, 'Bundt cake'
EXEC addProductToOrder 74, 2, 'Biscuit stick'
EXEC addProductToOrder 74, 1, 'Cloves'
EXEC addProductToOrder 74, 2, 'Corn salad'
EXEC addProductToOrder 74, 1, 'Chicken and dumplings'
EXEC addProductToOrder 74, 3, 'Baked stuffed shrimp'
EXEC addProductToOrder 75, 2, 'Apple pudding'
EXEC addProductToOrder 75, 1, 'Bun'
EXEC addProductToOrder 75, 1, 'Pasta with tuna'
EXEC addProductToOrder 75, 2, 'Pasta with broccoli'
EXEC addProductToOrder 75, 2, 'Raspberry juice'
EXEC addProductToOrder 76, 2, 'Cookie stick'
EXEC addProductToOrder 76, 3, 'Matcha tea'
EXEC addProductToOrder 76, 2, 'Mango'
EXEC addProductToOrder 76, 2, 'Apple'
EXEC addProductToOrder 76, 3, 'Hummus'
EXEC addProductToOrder 77, 2, 'Biscuit sandwich roll'
EXEC addProductToOrder 77, 2, 'American cheese'
EXEC addProductToOrder 77, 1, 'Mate tea'
EXEC addProductToOrder 77, 1, 'Strawberry juice'
EXEC addProductToOrder 77, 3, 'Café de olla'
EXEC addProductToOrder 78, 1, 'Anise'
EXEC addProductToOrder 78, 3, 'American cheese'
EXEC addProductToOrder 78, 2, 'Shrimp scampi served over pasta'
EXEC addProductToOrder 78, 3, 'Baked stuffed clams'
EXEC addProductToOrder 78, 3, 'Lemon custard'
EXEC addProductToOrder 79, 2, 'Pecan'
EXEC addProductToOrder 79, 3, 'Fish stick'
EXEC addProductToOrder 79, 2, 'Grape juice'
EXEC addProductToOrder 79, 1, 'Americano'
EXEC addProductToOrder 79, 2, 'Chocolate pudding'
EXEC addProductToOrder 80, 3, 'Pasta with mussels'
EXEC addProductToOrder 80, 3, 'Café Cubano'
EXEC addProductToOrder 80, 2, 'Lobster tail with drawn butter'
EXEC addProductToOrder 80, 2, 'Fish sandwich'
EXEC addProductToOrder 80, 1, 'Brown sauce'
EXEC addProductToOrder 81, 1, 'Walnut'
EXEC addProductToOrder 81, 1, 'Pasta with crab'
EXEC addProductToOrder 81, 1, 'Bundt cake'
EXEC addProductToOrder 81, 1, 'Biscuit roll'
EXEC addProductToOrder 81, 1, 'Potato salad'
EXEC addProductToOrder 82, 2, 'Butter'
EXEC addProductToOrder 82, 2, 'Pistachio'
EXEC addProductToOrder 82, 1, 'Allspice'
EXEC addProductToOrder 82, 2, 'Pasta with spinach'
EXEC addProductToOrder 82, 1, 'Vanilla pudding'
EXEC addProductToOrder 83, 3, 'Bisque sauce'
EXEC addProductToOrder 83, 1, 'Baked stuffed squash'
EXEC addProductToOrder 83, 1, 'Cookie sandwich stick'
EXEC addProductToOrder 83, 1, 'Chocolate ice cream'
EXEC addProductToOrder 83, 2, 'Beef casserole'
EXEC addProductToOrder 84, 3, 'Cinnamon'
EXEC addProductToOrder 84, 3, 'Diet 7 Up'
EXEC addProductToOrder 84, 1, 'Lime'
EXEC addProductToOrder 84, 1, 'Fried mozzarella sticks'
EXEC addProductToOrder 84, 3, 'Fried mushrooms'
EXEC addProductToOrder 85, 2, 'Romano cheese'
EXEC addProductToOrder 85, 3, 'Bisque sauce'
EXEC addProductToOrder 85, 1, 'Chef salad'
EXEC addProductToOrder 85, 1, 'Bleu cheese'
EXEC addProductToOrder 85, 3, 'Dip'
EXEC addProductToOrder 86, 3, 'Matcha tea'
EXEC addProductToOrder 86, 2, 'Minestrone soup'
EXEC addProductToOrder 86, 2, 'Strawberry ice cream'
EXEC addProductToOrder 86, 3, 'Biscuit'
EXEC addProductToOrder 86, 1, 'Carrot cake'
EXEC addProductToOrder 87, 2, 'Lime'
EXEC addProductToOrder 87, 3, 'Vanilla pudding'
EXEC addProductToOrder 87, 1, 'Asiago cheese'
EXEC addProductToOrder 87, 3, 'Café mélange'
EXEC addProductToOrder 87, 2, 'Biscuit stick'
EXEC addProductToOrder 88, 3, 'Pasta with shrimp'
EXEC addProductToOrder 88, 3, 'Baked stuffed squash'
EXEC addProductToOrder 88, 1, 'Apple pudding'
EXEC addProductToOrder 88, 3, 'Vegetable stew'
EXEC addProductToOrder 88, 1, 'Beef soup'
EXEC addProductToOrder 89, 2, 'Cookie'
EXEC addProductToOrder 89, 3, 'Diet 7 Up'
EXEC addProductToOrder 89, 3, 'Chocolate'
EXEC addProductToOrder 89, 3, 'Crab cakes with a remoulade sauce'
EXEC addProductToOrder 89, 3, 'Lentil soup'
EXEC addProductToOrder 90, 2, 'Chicken and mushroom soup'
EXEC addProductToOrder 90, 2, 'Café marrón'
EXEC addProductToOrder 90, 2, 'Cereal stick'
EXEC addProductToOrder 90, 3, 'Avocado salad'
EXEC addProductToOrder 90, 3, 'Walnut'
EXEC addProductToOrder 91, 2, 'Potato salad'
EXEC addProductToOrder 91, 2, 'Honeybush tea'
EXEC addProductToOrder 91, 2, 'Cashew'
EXEC addProductToOrder 91, 3, 'Strawberry ice cream'
EXEC addProductToOrder 91, 3, 'Dr Pepper'
EXEC addProductToOrder 92, 1, 'Cloves'
EXEC addProductToOrder 92, 2, 'Chicken and wild rice soup'
EXEC addProductToOrder 92, 1, 'Chicken and rice soup'
EXEC addProductToOrder 92, 2, 'Fried pickles'
EXEC addProductToOrder 92, 3, 'Gruyere cheese'
EXEC addProductToOrder 93, 3, 'Allspice'
EXEC addProductToOrder 93, 2, 'Provolone cheese'
EXEC addProductToOrder 93, 2, 'Black tea'
EXEC addProductToOrder 93, 2, 'Coconut'
EXEC addProductToOrder 93, 3, 'Angel food cake'
EXEC addProductToOrder 94, 2, 'Fish sandwich roll'
EXEC addProductToOrder 94, 2, 'Cardamom'
EXEC addProductToOrder 94, 2, 'Beef stew with cabbage'
EXEC addProductToOrder 94, 2, 'Cheddar cheese'
EXEC addProductToOrder 94, 2, 'Rooibos tea'
EXEC addProductToOrder 95, 3, 'Cookie sandwich stick'
EXEC addProductToOrder 95, 2, 'Gouda cheese'
EXEC addProductToOrder 95, 3, 'Chutney sauce'
EXEC addProductToOrder 95, 3, 'Goat cheese'
EXEC addProductToOrder 95, 2, 'Baked stuffed squash'
EXEC addProductToOrder 96, 1, 'Baked brie'
EXEC addProductToOrder 96, 1, 'Oolong tea'
EXEC addProductToOrder 96, 3, 'Café gourmand'
EXEC addProductToOrder 96, 3, 'Banana cake'
EXEC addProductToOrder 96, 1, 'Clam chowder'
EXEC addProductToOrder 97, 2, 'Coriander'
EXEC addProductToOrder 97, 1, 'Cookie sandwich roll'
EXEC addProductToOrder 97, 1, 'Angel food cake'
EXEC addProductToOrder 97, 1, 'Pistachio'
EXEC addProductToOrder 97, 1, 'Coconut cake'
EXEC addProductToOrder 98, 2, 'Avocado salad'
EXEC addProductToOrder 98, 3, 'Peach pudding'
EXEC addProductToOrder 98, 3, 'Kombucha tea'
EXEC addProductToOrder 98, 3, 'Butter roll'
EXEC addProductToOrder 98, 3, 'Fried mozzarella sticks'
EXEC addProductToOrder 99, 3, 'Orange'
EXEC addProductToOrder 99, 1, 'Asparagus salad'
EXEC addProductToOrder 99, 1, 'Goat cheese'
EXEC addProductToOrder 99, 2, 'Bundt cake'
EXEC addProductToOrder 99, 2, 'Strawberry ice cream'