EXEC AddPaymentStatus 'Paid in full'
EXEC AddPaymentStatus 'Partial payment received'
EXEC AddPaymentStatus 'Payment pending'
EXEC AddPaymentStatus 'Payment overdue'
EXEC AddPaymentStatus 'Payment failed'
EXEC AddPaymentStatus 'Payment refunded'
EXEC AddPaymentStatus 'Payment cancelled'
EXEC AddPaymentStatus 'Payment in process'
EXEC AddPaymentStatus 'Payment on hold'
EXEC AddPaymentStatus 'Payment not required'
EXEC AddPaymentStatus 'Payment not accepted'
EXEC AddPaymentStatus 'Payment not applicable'
EXEC AddPaymentStatus 'Payment not authorized'
EXEC AddPaymentStatus 'Payment received'
EXEC AddPaymentStatus 'Payment submitted'
EXEC AddPaymentStatus 'Payment confirmed'
EXEC AddPaymentStatus 'Payment processed'
EXEC AddPaymentStatus 'Payment completed'
EXEC AddPaymentStatus 'Payment acknowledged'
EXEC AddPaymentStatus 'Payment reconciled'
EXEC AddPaymentStatus 'Payment settled'
EXEC AddPaymentStatus 'Payment verified'
EXEC AddPaymentStatus 'Payment approved'
EXEC AddPaymentStatus 'Payment declined'
EXEC AddPaymentStatus 'Payment rejected'
EXEC AddPaymentStatus 'Payment disputed'
EXEC AddPaymentStatus 'Payment cancelled by customer'
EXEC AddPaymentStatus 'Payment cancelled by merchant'
EXEC AddPaymentStatus 'Payment delayed'
EXEC AddPaymentStatus 'Payment re-submitted'
EXEC AddPaymentStatus 'Payment rescheduled'
EXEC AddPaymentStatus 'Payment refund requested'
EXEC AddPaymentStatus 'Payment refunded partially'
EXEC AddPaymentStatus 'Payment refunded in full'
EXEC AddPaymentStatus 'Payment in transit'
EXEC AddPaymentStatus 'Payment in dispute'
EXEC AddPaymentStatus 'Payment under review'
EXEC AddPaymentStatus 'Payment not yet cleared'
EXEC AddPaymentStatus 'Payment not yet processed'
EXEC AddPaymentStatus 'Payment not yet approved'
EXEC AddPaymentStatus 'Payment not yet completed'
EXEC AddPaymentStatus 'Payment not yet reconciled'
EXEC AddPaymentStatus 'Payment not yet settled'
EXEC AddPaymentStatus 'Payment not yet verified'
EXEC AddPaymentStatus 'Payment not yet acknowledged'
EXEC AddPaymentStatus 'Payment not yet acknowledged by bank'
EXEC AddPaymentStatus 'Payment not yet acknowledged by merchant'
EXEC AddPaymentStatus 'Payment not yet acknowledged by customer'
EXEC AddPaymentStatus 'Payment not yet acknowledged by system'
EXEC AddPaymentStatus 'Payment not yet acknowledged by payment gateway'
EXEC AddPaymentStatus 'Payment not yet acknowledged by financial institution'
EXEC AddPaymentStatus 'Payment not yet acknowledged by processor'
EXEC AddPaymentStatus 'Payment not yet acknowledged by issuer'
EXEC AddPaymentStatus 'Payment not yet acknowledged by acquirer'
EXEC AddPaymentStatus 'Payment not yet acknowledged by network'
EXEC AddPaymentStatus 'Payment not yet acknowledged by clearing house'
EXEC AddPaymentStatus 'Payment not yet acknowledged by settlement institution'