INSERT INTO Project.dbo.PaymentMethods
    VALUES
('Bitcoin'),
('Litecoin'),
('Ethereum'),
('Ripple'),
('Cashiers check'),
('Money order'),
('Electronic funds transfer (EFT)'),
('Direct deposit'),
('Wire transfer'),
('Google Pay'),
('Amazon Pay'),
('AliPay'),
('WeChat Pay'),
('Samsung Pay'),
('Snapcash'),
('Venmo QR code'),
('Square Cash'),
('Dwolla'),
('Cash App'),
('Zelle'),
('Xoom'),
('MoneyGram'),
('Western Union'),
('Postal order'),
('Demand draft'),
('Paytm'),
('UPI'),
('NEFT'),
('RTGS'),
('Cash'),
('Credit card'),
('debit card'),
('Mobile payment'),
('Check'),
('Bank transfer'),
('PayPal'),
('Venmo'),
('Apple Pay')